[[index]]
= Introduction
:page-aliases: introduction.adoc
:description: An introduction to the Neo4j GraphQL Library.

The Neo4j GraphQL Library is:

* highly flexible and low-code
* open source
* a JavaScript library
* leveraging graph-native data

It enables rapid API development for cross-platform and mobile applications.

== How it works

The Neo4j GraphQL Library requires a set of type definitions that describes the shape of your graph data and creates an API layer to communicate with the data.

It generates an entire executable schema with all additional types needed to execute queries and mutations to interact with your Neo4j database.

For example, consider these type definitions:

[source, graphql, indent=0]
----
type Product @node {
    productName: String
    category: [Category!]! @relationship(type: "PART_OF", direction: OUT)
}

type Category @node {
    categoryName: String
    products: [Product!]! @relationship(type: "PART_OF", direction: IN)
}
----

Based on these type definitions, the library generates query and mutation templates to create new instances of the types as well as query existing instances.

The following mutation creates a new product as well as a new category:

[source, graphql, indent=0]
----
mutation {
  createProducts(
    input: [
      {
        productName: "New Product"
        category: { create: [{ node: { categoryName: "New Category" } }] }
      }
    ]
  ) {
    products {
      productName
      category {
        categoryName
      }
    }
  }
}
----

Here is an example of how you can query existing data:

[source, graphql, indent=0]
----
query {
  products {
    productName
    category {
      categoryName
    }
  }
}
----

See xref:using-the-library.adoc[] to learn how to use the GraphQL Library in your technology stack.
Check out xref:getting-started/index.adoc[] to create a new project, either based on Neo4j Aura or self-hosted.


== Resources

. https://github.com/neo4j/graphql[GitHub]
. https://github.com/neo4j/graphql/issues[Issue Tracker]
. https://www.npmjs.com/package/@neo4j/graphql[npm package]


== License

ifndef::backend-pdf[]
Documentation license: link:{common-license-page-uri}[Creative Commons 4.0]
endif::[]

ifdef::backend-pdf[]
(C) {copyright}

Documentation license: <<license, Creative Commons 4.0>>
endif::[]
Source: https://www.apache.org/licenses/LICENSE-2.0[Apache 2.0]

// Edit at: https://github.com/neo4j-graphacademy/courses/blob/main/asciidoc/courses/graphql-basics/promo.adoc
include::https://raw.githubusercontent.com/neo4j-graphacademy/courses/main/asciidoc/courses/graphql-basics/promo.adoc[]
