[[index]]
= Introduction
:page-aliases: introduction.adoc
:description: This section describes the Neo4j GraphQL Library.

The Neo4j GraphQL Library is a highly flexible, low-code, open source JavaScript library that enables rapid API development for cross-platform and mobile applications by tapping into the power of connected data.

With Neo4j as the graph database, the GraphQL Library makes it simple for applications to have data treated as a graph natively from the frontend all the way to storage.
This avoids duplicate schema work and ensures flawless integration between frontend and backend developers.

[.promo.promo-graphacademy]
====
*If you are new to Neo4j and GraphQL*, take the course link:https://graphacademy.neo4j.com/courses/graphql-basics/?ref=docs[Introduction to Neo4j & GraphQL] in GraphAcademy to learn the fundamentals, how to use the xref:getting-started/toolbox.adoc[Neo4j GraphQL Toolbox] and the Neo4j GraphQL Library to create GraphQL APIs backed by a Neo4j graph database.
====

[NOTE]
====
The GRANDstack starter app has been deprecated. 
For more information, read the section on xref::deprecations.adoc[Deprecations].
====

== How it works

The Neo4j GraphQL Library requires a set of type definitions that describes the shape of your graph data.
It can generate an entire executable schema with all of the additional types needed to execute queries and mutations to interact with your Neo4j database.

For every query and mutation that is executed against this generated schema, the Neo4j GraphQL Library generates a single Cypher query which is executed against the database. This eliminates the https://www.google.com/search?q=graphql+n%2B1[N+1 Problem], which can make GraphQL implementations slow and inefficient.

- Automatic generation of xref::queries-aggregations/queries.adoc[Queries] and xref::mutations/index.adoc[Mutations] for CRUD interactions.
- xref::/types/index.adoc[Types], including temporal and spatial.
- Support for both node and relationship properties.
- Extensibility through the xref::/directives/custom-logic.adoc#_cypher[`@cypher` directive] and/or xref::/directives/custom-logic.adoc#_custom-resolvers[Custom Resolvers].
- Extensive xref::queries-aggregations/filtering.adoc[Filtering] and xref::queries-aggregations/sorting.adoc[Sorting] options.
- Options for xref::/directives/database-mapping.adoc[Database mapping] and value xref::/directives/autogeneration.adoc[Autogeneration].
- xref::/queries-aggregations/pagination/index.adoc[Pagination] options.
- xref::/security/index.adoc[Security options] and additional xref::schema-configuration/index.adoc[Schema Configuration].
- An xref::ogm/index.adoc[OGM] (Object Graph Mapper) for programmatic interaction with your GraphQL API.
- A xref::getting-started/toolbox.adoc[Toolbox] (UI) to experiment with your Neo4j GraphQL API on Neo4j Desktop.


== Interaction

In the xref::getting-started/index.adoc[Getting Started] guide, Apollo Server is used to host the GraphQL schema, so you can interact directly with your API with no frontend.
In case you prefer to use frontend frameworks, these are some clients that interact with GraphQL APIs:

- https://reactjs.org/[React] - support through https://www.apollographql.com/docs/react/[Apollo Client]
- https://vuejs.org/[Vue.js] - support through https://apollo.vuejs.org/[Vue Apollo]
- https://angularjs.org/[AngularJS] - support through https://apollo-angular.com/docs/[Apollo Angular].

== Deployment

There are a variety of methods for deploying GraphQL APIs.
In the xref::getting-started/index.adoc[Getting Started] guide, Apollo Server is being used for demonstration.
You can check their own documentation about https://www.apollographql.com/docs/apollo-server/deployment[Deployment] for more details.

== Versioning

The Neo4j GraphQL Library uses https://semver.org/[Semantic Versioning]. 
Given a version number `MAJOR.MINOR.PATCH`, the increment is based on:

- `MAJOR` - incompatible API changes compared to the previous `MAJOR` version, for which you will likely have to migrate
- `MINOR` - new features have been added in a backwards compatible manner
- `PATCH` - bug fixes have been added in a backwards compatible manner.

Additionally, prerelease version numbers may have additional suffixes, for example `MAJOR.MINOR.PATCH-PRERELEASE.NUMBER`, where `PRERELEASE` is one of the following:

- `alpha` - unstable prerelease artifacts, and the API may change between releases during this phase
- `beta` - feature complete prerelease artifacts, which will be more stable than `alpha` releases but will likely still contain bugs
- `rc` - release candidate including artifacts to be promoted to a stable release, in a last effort to find trailing bugs.

`NUMBER` in the suffix is simply an incrementing release number in each phase.

== Requirements

. https://neo4j.com/[Neo4j Database] version 4.4 and newer with https://neo4j.com/docs/apoc/current/[APOC] plugin.
. https://nodejs.org/en/[Node.js] 16+.

== Resources

. https://github.com/neo4j/graphql[GitHub]
. https://github.com/neo4j/graphql/issues[Issue Tracker]
. https://www.npmjs.com/package/@neo4j/graphql[npm package]

== License

ifndef::backend-pdf[]
Documentation license: link:{common-license-page-uri}[Creative Commons 4.0]
endif::[]

ifdef::backend-pdf[]
(C) {copyright}

Documentation license: <<license, Creative Commons 4.0>>
endif::[]
Source: https://www.apache.org/licenses/LICENSE-2.0[Apache 2.0]
