= The `Neo4jGraphQL` class
:description: This section describes various setting field in the Neo4j GraphQL main class.

You can assign different setting fields in the Neo4jGraphQL constructor: 

[source, javascript, indent=0]
----
export interface Neo4jGraphQLConstructor {
    typeDefs: TypeDefinitions; <1>
    resolvers?: IExecutableSchemaDefinition["resolvers"]; <2>
    features?: Neo4jFeaturesSettings; <3>
    driver?: Driver; <4>
    debug?: boolean;
    validate?: boolean;
}
----
<1> See xref:types/index.adoc[].
<2> See xref:directives/custom-logic.adoc#_customresolver[Custom resolvers].
<3> See xref:#_feature_settings[] on this page.
<4> See xref:driver-configuration.adoc[].


== Feature settings

You can set different features in the `features` field of the Neo4j GraphQL constructor.
The `Neo4jFeaturesSettings` type looks like this:

[source, javascript, indent=0]
----
export type Neo4jFeaturesSettings = {
    filters?: Neo4jFiltersSettings;
    populatedBy?: Neo4jPopulatedBySettings;
    authorization?: Neo4jAuthorizationSettings;
    subscriptions?: Neo4jGraphQLSubscriptionsEngine | boolean;
    /** If set to `true`, removes `@neo4j/graphql` fields that are marked as deprecated to reduce schema size.
     *
     * NOTE: this will not remove user defined deprecated fields
     **/
    excludeDeprecatedFields?: {
        mutationOperations?: boolean;
        aggregationFilters?: boolean;
        aggregationFiltersOutsideConnection?: boolean;
        relationshipFilters?: boolean;
        attributeFilters?: boolean;
    };
    vector?: Neo4jVectorSettings;
    limitRequired?: boolean;
    complexityEstimators?: boolean;
};
----


=== Filter settings

Use `Neo4jFiltersSettings` to enable numeric String comparisons and regular expression filters for Strings and IDs.
They are disabled by default.
See xref:filtering.adoc#_string_comparison[String comparison] and xref:filtering.adoc#_regex_matching[RegEx matching].


=== `populatedBy` settings

Use the `populatedBy` field to register callback functions used by the `@populatedBy` directive.
See xref:directives/custom-logic.adoc#_populatedby[`@populatedBy`].


=== Authorization settings

Set authorization keys in the `authorization` field.
See xref:security/configuration.adoc[Security > Configuration].


=== Subscription settings

Enable the `subscriptions` feature of the Neo4j GraphQL Library by setting it to `true`.
It is also used to provide subscription settings. See xref:subscriptions/customize-cdc.adoc[Subscription engines].

=== Exclude deprecated fields

If you are not using them, use `excludeDeprecatedFields` to disable the generation of various deprecated fields.
See xref:optimization.adoc#_exclude_deprecated_fields[Exclude `@deprecated` fields].


=== Vector settings

Set your GenAI provider credentials with the `vector` field.
See xref:directives/indexes-and-constraints.adoc#_vector_index_search[`@vector`].


=== Limit required settings

Set `limitRequired` to `true` to require a `limit` argument for all read operations that return lists.
This is useful to prevent unbounded queries that can lead to performance issues.
See xref:security/avoid-unbounded-queries.adoc#_limit_required[Avoid unbounded queries > Require `limit` argument].


=== Complexity estimators settings

Set `complexityEstimators` to `true` to enable the assignment of a complexity "score" to each field in the schema.
This feature creates complexity estimators compatible with the link:https://www.npmjs.com/package/graphql-query-complexity[graphql-query-complexity] library, which can be used to generate the total complexity score of an incoming query via the `getComplexity` function.
See xref:security/avoid-unbounded-queries.adoc#_complexity_estimators[Avoid unbounded queries > Complexity estimators].