[[schema-configuration-global-configuration]]
= Global configuration
:page-aliases: type-definitions/schema-configuration/global-configuration.adoc, schema-configuration/global-configuration.adoc
:description: This page describes how to globally disable specific types of operations.


Through the schema configuration, it is possible to globally disable specific types of operation.
To set up operations individually, refer to xref:/schema-configuration/type-configuration.adoc[Type Configuration].

For instance, if you want *to disable all top-level aggregation operations at once*, the Neo4j GraphQL Library offers this option through schema extensions with `@query`:

[source, graphql, indent=0]
----
type Movie @node { 
    title: String 
    actors: [Actor!]! @relationship(type: "ACTED_IN", direction: IN) 
} 

type Actor @node { 
    name: String 
    movies: [Movie!]! @relationship(type: "ACTED_IN", direction: OUT) 
}
extend schema @query(read: true, connection: true, aggregate: false)
----

This configuration disables all top-level aggregation operations for the `Movie` and `Actor` types, while still allowing read operations.

[source, graphql, indent=0]
----
type Query {
  moviesConnection(first: Int, after: String, where: MovieWhere, sort: [MovieSort!]): MoviesConnection!
  movies(where: MovieWhere, limit: Int, offset: Int, sort: [MovieSort!]): [Movie!]!
  actorsConnection(first: Int, after: String, where: ActorWhere, sort: [ActorSort!]): ActorsConnection!
  actors(where: ActorWhere, limit: Int, offset: Int, sort: [ActorSort!]): [Actor!]!
}

type MoviesConnection {
  edges: [MovieEdge!]!
  totalCount: Int!
  pageInfo: PageInfo!
}

type ActorsConnection {
  edges: [ActorEdge!]!
  totalCount: Int!
  pageInfo: PageInfo!
}
----

**Invalid schema usage**

The same schema configuration directive cannot be applied to both schema and object.
Take the following type definitions as example:

[source, graphql, indent=0]
----
type Movie @node { 
    title: String 
    actors: [Actor!]! @relationship(type: "ACTED_IN", direction: IN) 
} 

type Actor @node @query(read: false, connection: false, aggregate: true) { 
    name: String 
    movies: [Movie!]! @relationship(type: "ACTED_IN", direction: OUT) 
}
extend schema @query(read: true, aggregate: false)
----

Such configuration prompts the error `"@query directive already defined at the schema location"`.
