[[schema-configuration-type-configuration]]
= Type configuration
:page-aliases: type-definitions/schema-configuration/type-configuration.adoc, schema-configuration/type-configuration.adoc
:description: This page describes how to reduce the operation fields produced using the directives @query, @mutation, and @subscription.


When representing a Neo4j node, a GraphQL Object Type produces multiple operation fields in the query, mutation, and subscription types.
For example:

[source, graphql, indent=0]
----
type Movie @node { 
    title: String 
    length: Int
}
----

From these type definitions, the library generates the following operation fields:

**Query**:

    * `movies`
    * `moviesConnection`

**Mutation**:

    * `createMovies`
    * `deleteMovies`
    * `updateMovies`

**Subscription**:

    * `movieCreated`
    * `movieUpdated`
    * `movieDeleted`

**moviesConnection**:

    * `aggregate`
    * `edges`
    * `totalCount`
    * `pageInfo`

This page describes how to reduce the operation fields produced using the directives `@query`, `@mutation`, and `@subscription`.

== `@query`

This directive is used to limit the availability of query operations in the library.

=== Definition

[source, graphql, indent=0]
----
directive @query(read: Boolean! = true, connection: Boolean, aggregate: Boolean! = false) on OBJECT | SCHEMA | INTERFACE | UNION
----

Where the value of the `connection` argument defaults to the value of the `read` argument.

=== Usage

.Disable query _movies_ and _moviesConnection_ edges field
[source, graphql, indent=0]
----
type Movie @node @query(read: false, aggregate: true) { 
    title: String 
    length: Int
}
----

.Disable _moviesConnection_ aggregate field
[source, graphql, indent=0]
----
type Movie @node @query(read: true, aggregate: false)  { # aggregate can be omitted as it defaults to false
    title: String 
    length: Int
}
----

.Disable _moviesConnection_ completely
[source, graphql, indent=0]
----
type Movie @node @query(read: true, connection: false, aggregate: false)  { # aggregate can be omitted as it defaults to false
    title: String 
    length: Int
}
----

.Disable all reads
[source, graphql, indent=0]
----
type Movie @node @query(read: false, aggregate: false)  { # aggregate can be omitted as it defaults to false
    title: String 
    length: Int
}
----

== `@mutation`

This directive is used to limit the availability of mutation operations in the library.

=== Definition

[source, graphql, indent=0]
----
enum MutationFields {
    CREATE
    UPDATE
    DELETE
}

directive @mutation(operations: [MutationFields!]! = [CREATE, UPDATE, DELETE]) on OBJECT | SCHEMA
----

=== Usage

.Disable Create, Delete, and Update operations for _Movie_
[source, graphql, indent=0]
----
type Movie @node @mutation(operations: []) { 
    title: String 
    length: Int
}
----

.Enable only Create operations for _Movie_
[source, graphql, indent=0]
----
type Movie @node @mutation(operations: [CREATE]) { 
    title: String 
    length: Int
}
----

== `@subscription`

This directive is used to enable subscription operations in the library. 
Subscriptions are opt-in by default, meaning that they are disabled unless explicitly enabled.

=== Definition

[source, graphql, indent=0]
----
enum SubscriptionFields {
    CREATED
    UPDATED
    DELETED
}

directive @subscription(events: [SubscriptionFields!]! = [CREATED, UPDATED, DELETE]) on OBJECT | SCHEMA
----

=== Usage

.Enable only _movieCreated_ subscription for _Movie_
[source, graphql, indent=0]
----
type Movie @node @subscription(events: [CREATED]) { 
    title: String 
    length: Int
}
----

.Enable subscriptions for all types except for _Movie_
[source, graphql, indent=0]
----
type Movie @node @subscription(events: [])  { 
    title: String 
    length: Int
}

type Actor @node  { 
    name: String 
    movies: [Movie!]! @relationship(type: "ACTED_IN", direction: OUT) 
}

extend schema @subscription
----

[[type-definitions-default-values-default]]
== `@default`

When generating the input type for the `create` mutation, the value specified in this directive is used as the default for the field.

=== Definition

[source, graphql, indent=0]
----
"""Int | Float | String | Boolean | ID | DateTime | Enum"""
scalar Scalar

"""Instructs @neo4j/graphql to set the specified value as the default value in the CreateInput type for the object type in which this directive is used."""
directive @default(
    """The default value to use. Must be a scalar type and must match the type of the field with which this directive decorates."""
    value: Scalar!,
) on FIELD_DEFINITION
----

=== Usage

`@default` may be used with enums. 
When setting the default value for an enum field, it must be one of the enumerated enum values:

[source, graphql, indent=0]
----
enum Location {
    HERE
    THERE
    EVERYWHERE
}

type SomeType @node {
    firstLocation: Location! @default(value: HERE) # valid usage
    secondLocation: Location! @default(value: ELSEWHERE) # invalid usage, will throw an error
}
----


== `@plural`

=== Definition

[source, graphql, indent=0]
----
"""
Instructs @neo4j/graphql to use the given value as the plural of the type name
"""
directive @plural(
  """The value to use as the plural of the type name."""
  value: String!
) on OBJECT | INTERFACE | UNION
----

=== Usage

This directive redefines how to compose the plural of the type for the generated operations.
This is particularly useful for types that are not correctly pluralized or are non-English words.
Take this type definition as an example:

[source, graphql, indent=0]
----
type Tech @plural(value: "Techs") @node {
  name: String
}
----

This way, instead of the wrongly generated `teches`, the type is properly written as `techs`:

[source, graphql, indent=0]
----
{
  techs {
    title
  }
}
----

The same is applied to other operations such as `createTechs`. 
However, keep in mind that database labels are not changed with this directive.
