[[type-definitions-types]]
= Scalar types
:page-aliases: type-definitions/types/scalar.adoc
:description: This page lists the default types available in the Neo4j GraphQL Library.

Neo4j GraphQL supports all of the built-in GraphQL https://graphql.org/learn/schema/#scalar-types[scalar types].
The `BigInt` scalar type is an addition specific to the Neo4j database.

== Scalar types

[cols="1,2,2"]
|===
| Type | Description | Example

| `Int`
| Supports up to 32-bit values.
a|
[source, graphql, indent=0]
----
type Person @node {
  age: Int!
}
----

.2+| `BigInt`
| Supports up to 64 bit integers, serialized as strings in variables and in data responses. 
Shares the same xref::queries-aggregations/filtering.adoc#_numerical_operators[Numerical operators] as the other numeric types.
a| 
[source, graphql, indent=0]
----
type File @node {
  size: BigInt
}
----

| Can be passed as a number (does not need quotes) when used directly in a query or mutation.
a|
[source, graphql, indent=0]
----
query {
    files(where: { size: 9223372036854775807 }) {
        size
    }
}
----

| `Float`
| Represents signed double‐precision fractional values.
a|
[source, graphql, indent=0]
----
type Product @node {
  price: Float!
}
----

| `String`
| Stored as a string in the database and always returned as a string.
a|
[source, graphql, indent=0]
----
type Product @node {
  name: String!
}
----

| `Boolean`
| Represents `true` or `false`.
a|
[source, graphql, indent=0]
----
type Product @node {
  inStock: Boolean!
}
----

| `ID`
| Represents a unique identifier.
a|
[source, graphql, indent=0]
----
type Product @node {
  id: ID!
}
----
|===
