
[[type-definitions-spatial-types]]
= Spatial types
:page-aliases: type-definitions/types/spatial.adoc
:description: This page lists the spatial types available in the Neo4j GraphQL Library.

== Spatial Types

Neo4j GraphQL spatial types translate to spatial values stored using https://neo4j.com/docs/cypher-manual/current/values-and-types/spatial/[`Point`] in the database. 
The use of either of these types in a GraphQL schema automatically introduces the types needed to run queries and mutations relevant to these spatial types.

[[point]]
=== `Point`

The `Point` type is used to describe the two https://neo4j.com/docs/cypher-manual/current/values-and-types/spatial/#spatial-values-crs-geographic[Geographic coordinate reference systems] supported by Neo4j.

In order to use it in your schema, add a field with a type `Point` to any other type(s) in your schema, like the following:

[source, graphql, indent=0]
----
 type TypeWithPoint @node {
    location: Point!
}
----

The `Point` type is automatically added to your schema, in addition to the input and output types that you need to query and manipulate spatial types through your API.

See xref::filtering.adoc#_spatial_type_filtering[Filtering spatial types] for filter options. 

==== Type definition

[source, graphql, indent=0]
----
type Point {
  longitude: Float!
  latitude: Float!
  height: Float
  crs: String!
  srid: Int!
}
----

==== Queries and mutations

Due to the fact that `Point` is an object type, it has an additional type for input in queries and mutations. 
However, these input types have the same shape as the object type:

[source, graphql, indent=0]
----
input PointInput {
    latitude: Float!
    longitude: Float!
    height: Float
}

input PointFilters {
  eq: PointInput
  in: [PointInput!]
  distance: PointDistanceFilters
}

input PointDistanceFilters {
  from: PointInput!
  gt: Float
  gte: Float
  lt: Float
  lte: Float
  eq: Float
}
----

For example, you can query for a `User` with an exact location:

[source, graphql, indent=0]
----
query Users($longitude: Float!, $latitude: Float!) {
    users(where: { location: { eq: { longitude: $longitude, latitude: $latitude } } }) {
        name
        location {
            longitude
            latitude
        }
    }
}
----

Or you can create a `User` with a location as follows:

[source, graphql, indent=0]
----
mutation CreateUsers($name: String!, $longitude: Float!, $latitude: Float!) {
    createUsers(input: [{ name: $name, location: { longitude: $longitude, latitude: $latitude } }]) {
        users {
            name
            location {
                longitude
                latitude
            }
        }
    }
}
----

[[cartesian-point]]
=== `CartesianPoint`

The `CartesianPoint` type is used to describe the two https://neo4j.com/docs/cypher-manual/current/values-and-types/spatial/#spatial-values-crs-cartesian[Cartesian coordinate reference systems] supported by Neo4j.

To use it in your schema, add a field with a type `CartesianPoint` to any type(s), such as in this example:

[source, graphql, indent=0]
----
type TypeWithCartesianPoint @node {
    location: CartesianPoint!
}
----

The `CartesianPoint` type is automatically added to your schema, in addition to the input and output types that you need to query and manipulate spatial types through your API.

See xref::filtering.adoc#_spatial_type_filtering[Filtering spatial types] for filter options.

==== Type definition

[source, graphql, indent=0]
----
type CartesianPoint {
  x: Float!
  y: Float!
  z: Float
  crs: String!
  srid: Int!
}
----

==== Queries and mutations

Due to the fact that `CartesianPoint` is an object type, it has an additional type for input in queries and mutations.
However, this input type has the same shape as the object type:

[source, graphql, indent=0]
----
input CartesianPointInput {
  x: Float!
  y: Float!
  z: Float
}

input CartesianPointFilters {
  eq: CartesianPointInput
  in: [CartesianPointInput!]
  distance: CartesianDistancePointFilters
}

input CartesianDistancePointFilters {
  from: CartesianPointInput!
  gt: Float
  gte: Float
  lt: Float
  lte: Float
}
----


For example, you can query for a `User` with an exact location:

[source, graphql, indent=0]
----
query Users($x: Float!, $y: Float!, $z: Float!) {
    users(where: { location: { eq: { x: $x, y: $y, z: $z } } }) {
        name
        location {
            x
            y
            z
        }
    }
}
----

Or you can create a `User` with a location as follows:

[source, graphql, indent=0]
----
mutation CreateUsers($name: String!, $x: Float!, $y: Float!, $z: Float!) {
    createUsers(input: [{ name: $name, location: { x: $x, y: $y, z: $z } }]) {
        users {
            name
            location {
                x
                y
                z
            }
        }
    }
}
----
