[[schema-configuration-type-configuration]]
= Type configuration
:page-aliases: type-definitions/schema-configuration/type-configuration.adoc
:description: This page describes how to reduce the operation fields produced using the directives @query, @mutation, and @subscription.


When representing a Neo4j node, a GraphQL Object Type produces multiple operation fields in the `Query`, `Mutation`, and `Subscription` types.
For example:

[source, graphql, indent=0]
----
type Movie { 
    title: String 
    length: Int
}
----

From these type definitions, the library generates the following operation fields:

**Query**:

    * `movies`
    * `moviesAggregate`
    * `moviesConnection`

**Mutation**:

    * `createMovies`
    * `deleteMovies`
    * `updateMovies`
    * `upsertMovies`

**Subscription**:

    * `movieCreated`
    * `movieUpdated`
    * `movieDeleted`
.

This page describes how to reduce the operation fields produced using the directives `@query`, `@mutation`, and `@subscription`.

== `@query`

This directive is used to limit the availability of query operations in the library.

=== Definition

[source, graphql, indent=0]
----
directive @query(read: Boolean! = true, aggregate: Boolean! = false) on OBJECT | SCHEMA
----

[NOTE]
====
Aggregations are no longer generated by default in the 4.0.0 version of the library. 
See xref:migration/index.adoc#_updated_directives[Updated directives] for more information.
====

=== Usage

.Disable _movies_ and _moviesConnection_ operations
[source, graphql, indent=0]
----
type Movie @query(read: false, aggregate: true) { 
    title: String 
    length: Int
}
----

.Disable _moviesAggregate_ operations
[source, graphql, indent=0]
----
type Movie @query(read: true, aggregate: false)  { 
    title: String 
    length: Int
}
----

== `@mutation`

This directive is used to limit the availability of mutation operations in the library.

=== Definition

[source, graphql, indent=0]
----
enum MutationFields {
    CREATE
    UPDATE
    UPSERT
    DELETE
}

directive @mutation(operations: [MutationFields!]! = [CREATE, UPDATE, UPSERT, DELETE]) on OBJECT | SCHEMA
----

=== Usage

.Disable Create, Update, Upsert and Delete operations for _Movie_
[source, graphql, indent=0]
----
type Movie @mutation(operations: []) { 
    title: String 
    length: Int
}
----

.Enable only Create operations for _Movie_
[source, graphql, indent=0]
----
type Movie @mutation(operations: [CREATE]) { 
    title: String 
    length: Int
}
----

== `@subscription`

This directive is used to limit subscription operations in the library.

=== Definition

[source, graphql, indent=0]
----
enum SubscriptionFields {
    CREATE
    UPDATE
    DELETE
    CREATE_RELATIONSHIP
    DELETE_RELATIONSHIP
}

directive @subscription(operations: [SubscriptionFields!]! = [CREATE, UPDATE, DELETE, CREATE_RELATIONSHIP, DELETE_RELATIONSHIP]) on OBJECT | SCHEMA
----

=== Usage

.Disable subscriptions for _Movie_
[source, graphql, indent=0]
----
type Movie @subscription(operations: [])  { 
    title: String 
    length: Int
}
----

.Enable only _movieCreated_ subscription for _Movie_
[source, graphql, indent=0]
----
type Movie @subscription(operations: [CREATE]) { 
    title: String 
    length: Int
}
----
