[[apollo-federation]]
:description: This guide shows how to create a subgraph using the Neo4j GraphQL Library, for composition into a supergraph using Apollo Federation.
= Create a subgraph compatible with Apollo Federation

This guide shows how to create a subgraph using the Neo4j GraphQL Library, for composition into a supergraph using Apollo Federation. 

The objective is to convert the following monolithic schema into a subgraph schema for use behind a Federation gateway:

[source, javascript]
----
import { ApolloServer } from "@apollo/server";
import { startStandaloneServer } from "@apollo/server/standalone";
import { Neo4jGraphQL } from "@neo4j/graphql";
import neo4j from "neo4j-driver";

const typeDefs = `#graphql
  type User {
    id: ID!
    name: String!
  }
`;

const {
  NEO4J_URI = "neo4j://localhost:7687/neo4j",
  NEO4J_USERNAME = "neo4j",
  NEO4J_PASSWORD = "password",
} = process.env;

const driver = neo4j.driver(NEO4J_URI, neo4j.auth.basic(NEO4J_USERNAME, NEO4J_PASSWORD));

const neo4jgraphql = new Neo4jGraphQL({
  typeDefs,
  driver,
})

const schema = await neo4jGraphQL.getSchema();

const server = new ApolloServer({
  schema,
});

const { url } = await startStandaloneServer(server);
console.log(`🚀  Server ready at ${url}`);
----

== Create a new project and install the Apollo Server

Follow the steps in xref::how-to-guides/create-project.adoc.

== 2. Install dependencies

The core dependencies for a Neo4j GraphQL Library have already been installed in your new project.

The final dependency to install is `@apollo/server`, the library for Apollo Server. It is used in this guide to host the subgraph.

Run the following command to install this final package:

[source, bash]
----
npm install @apollo/server
----

== Opt in to Federation

For a set of type definitions to be usable as a subgraph for Federation, they must include the following schema extension:

[source, javascript]
----
const typeDefs = `#graphql
  extend schema @link(url: "https://specs.apollo.dev/federation/v2.0", import: ["@key"])

  type User {
    id: ID!
    name: String!
  }
`;
----

Note that this example only includes the Federation `@key` directive. 
To use more https://www.apollographql.com/docs/federation/federated-types/federated-directives[Federation directives], add them to the `import` array.

== Define an entity

Defining a type as an https://www.apollographql.com/docs/federation/entities/[entity] allows other subgraphs to contribute with fields to the `Movie` type.
To achieve that, use the `@key` directive to designate a field (or fields) as a key:

[source, javascript]
----
const typeDefs = `#graphql
  extend schema @link(url: "https://specs.apollo.dev/federation/v2.0", import: ["@key"])

  type User @key(fields: "id") {
    id: ID!
    name: String!
  }
`;
----

Although only the `@key` directive has been added to this example, consider using either the `@id` or the `@unique` directives on the `id` field.
The Federation gateway expects each key to resolve to one result, so it is good practice to ensure that these values are unique in the database.

== Generate a subgraph schema

When using the Neo4j GraphQL Library, generating the subgraph schema can be achieved by calling `getSubgraphSchema` instead of `getSchema`.
In other words, only the following line needs to be changed:

[source, javascript]
----
const schema = neo4jgraphql.getSubgraphSchema();
----

== Conclusion

By combining all previous snippets, you should get this:

[source, javascript]
----
import { ApolloServer } from "@apollo/server";
import { startStandaloneServer } from "@apollo/server/standalone";
import { Neo4jGraphQL } from "@neo4j/graphql";

const typeDefs = `#graphql
  type User @key(fields: "id") {
    id: ID!
    name: String!
  }
`;

const {
  NEO4J_URI = "neo4j://localhost:7687/neo4j",
  NEO4J_USERNAME = "neo4j",
  NEO4J_PASSWORD = "password",
} = process.env;

const driver = neo4j.driver(NEO4J_URI, neo4j.auth.basic(NEO4J_USERNAME, NEO4J_PASSWORD));

const neo4jgraphql = new Neo4jGraphQL({
  typeDefs,
  driver,
})

const schema = await neo4jGraphQL.getSubgraphSchema();

const server = new ApolloServer({
  schema,
});

const { url } = await startStandaloneServer(server);
console.log(`🚀  Server ready at ${url}`);
----


For further iteration, this subgraph can also be composed into a supergraph. 
Check Apollo's guides for more instructions:

* https://www.apollographql.com/docs/federation/quickstart/studio-composition[Composition in Apollo Studio]
* https://www.apollographql.com/docs/federation/quickstart/local-composition[Local composition]
