[[authorization]]
:description: This page describes how to set up authorization features in the Neo4j GraphQL Library.
= Authorization

Authorization rules cover to what specific data a generated Cypher query is executed against.
They use predicates to evaluate the Cypher generated from a GraphQL query, thus allowing or not execution within the context of nodes and their properties.

All authorization rules have an implied requirement for authentication, given that the rules are normally evaluated against values in the JWT payload.

In the case of explicit authentication, configured using the `@authentication` directive, it is only ever evaluated during Cypher translation time.
Unauthenticated requests with queries requiring authentication never reach the database.

== Rules

=== Filtering

Filtering rules filter out data which users do not have access to, without throwing any errors. 
These rules are evaluated in the database, then translated into filtering predicates that are evaluated against matched data.

Filtering rules protect data as well as obfuscate the information on the _existence_ of that data to unauthorized users.

For instance, here is how to filter out `Post` nodes which don't belong to the current `User`:

[source, graphql, indent=0]
----
type User {
    id: ID!
}

type Post @authorization(filter: [
    { where: { node: { author: { id: "$jwt.sub" } } } }
]) {
    title: String!
    content: String!
    author: User! @relationship(type: "AUTHORED", direction: IN)
}
----

=== Validating

Validating rules throw an error if a query is executed against data which users do not have access to. 
These rules are evaluated in the database via filtering predicates containing calls to 
https://neo4j.com/docs/apoc/current/overview/apoc.util/apoc.util.validatePredicate/[`apoc.util.validatePredicate`].

For instance, here is how to throw an error if a `User` is accessed by anyone but the user themselves or an admin:

[source, graphql, indent=0]
----
type JWT @jwt {
    roles: [String!]!
}

type User @authorization(validate: [
    { where: { node: { id: "$jwt.sub" } } }
    { where: { jwt: { roles_INCLUDES: "admin" } } }
]) {
    id: ID!
}
----

== Authorization without authentication

Authentication is implicitly required for every authorization check by default, but this can be disabled on a per-rule basis.
This could be the case, for instance, when a node has a property which flags whether the node should be public or not.

For instance, in case `Post` nodes might be private and belong to a particular `User`, or be public and readable by any user, here is how to set this up:

[source, graphql, indent=0]
----
type User {
    id: ID!
}

type Post @authorization(filter: [
    { where: { node: { author: { id: "$jwt.sub" } } } }
    { requireAuthentication: false, operations: [READ], where: { node: { public: true } } }
]) {
    title: String!
    content: String!
    public: Boolean!
    author: User! @relationship(type: "AUTHORED", direction: IN)
}
----
