= How to create a new project

This guide shows you how to create a new project.

This how-to guide assumes that you are familiar with the command line and JavaScript, and have https://nodejs.org/en[Node.js LTS] installed. The how-to guide contains options for both JavaScript and TypeScript.

== 1. Create the project directory

Create a directory for a new project and `cd` into it:

[source, bash]
----
mkdir neo4j-graphql-subgraph-example
cd neo4j-graphql-subgraph-example
----

== 2. Initialize the project

Initialize a new Node.js project with `npm`:

[source, bash]
----
npm init --yes
npm pkg set type="module"
----

NOTE: This how-to guide sets up the project using ES Modules, which allows the usage of features such as top-level `await`.

== 3. Language specific setup

Follow the instructions below to set up with either TypeScript or JavaScript:

.TypeScript
[%collapsible]
====
. Create a `src` directory with an empty `index.ts` file to contain the entrypoint to your code for this project:
+
[source, bash]
----
mkdir src
touch src/index.ts
----
+
. Install the development dependencies required for working with a TypeScript project:
+
[source, bash]
----
npm install --save-dev typescript @types/node @tsconfig/node-lts
----
+
. Create an empty `tsconfig.json` file which will contain the compiler configuration for TypeScript:
+
[source, bash]
----
touch tsconfig.json
----
+
. Add the following configuration to the `tsconfig.json` file created above:
+
[source, json]
----
{
  "extends": "@tsconfig/node-lts/tsconfig.json",
  "compilerOptions": {
    "rootDir": "src",
    "outDir": "dist",
  }
}
----
+
NOTE: The configuration above extends the https://github.com/tsconfig/bases#node-lts-tsconfigjson[community base for Node.js LTS], provided by the `@tsconfig/node-lts` package installed above. For more information on the available options, see the https://www.typescriptlang.org/tsconfig[TypeScript Compiler docs]. 
+
. Replace the default `scripts` entry in your `package.json` file with the following `scripts` entry:
+
[source, json]
----
{
  // ...etc.
  "scripts": {
    "compile": "tsc",
    "start": "npm run compile && node ./dist/index.js"
  }
  // other dependencies
}
----
====

.JavaScript
[%collapsible]
====
. Create a `src` directory with an empty `index.js` file to contain the entrypoint to your code for this project:
+
[source, bash]
----
mkdir src
touch src/index.js
----
+
. Replace the default `scripts` entry in your `package.json` file with the following `scripts` entry:
+
[source, json]
----
{
  // ...etc.
  "scripts": {
    "start": "node index.js"
  }
  // other dependencies
}
----
====

== 4. Install dependencies

The following dependencies are always required when using the Neo4j GraphQL Library:

* `@neo4j/graphql` is the Neo4j GraphQL Library, which translates GraphQL into Cypher and returns the results.
* `graphql` is the reference implementation of the GraphQL specification. It is required for `@neo4j/graphql` to function.
* `neo4j-driver` is the library for the Neo4j driver, which is required to execute Cypher queries against the database.

Install these dependencies by running the following command:

[source, bash]
----
npm install @neo4j/graphql graphql neo4j-driver
----
