[[ogm]]
:description: This section describes how to use the OGM functionality in Neo4j GraphQL.
:page-aliases: ogm/examples.adoc
= OGM

Most applications don't only expose a single GraphQL API -- there may also be scheduled jobs, authentication, and migrations keeping an application on.
The OGM (Object Graph Mapper) can be used to programmatically interact with your Neo4j GraphQL API, so you can achieve these goals.

This section includes:

* xref::ogm/installation.adoc[Installation] - How to install the OGM and usage examples.
* xref::ogm/directives.adoc[Directives] - How to use directives in OGM.
* xref::ogm/selection-set.adoc[Selection set] - How to use this GraphQL functionality in OGM.
* xref::ogm/type-generation.adoc[TypeScript Type Generation] - How to generate types in Neo4j GraphQL using TypeScript.
* xref::ogm/reference.adoc[API Reference] - Reference guide to all functionalities in OGM.

[NOTE]
====
Before using the OGM, it's recommended that you have a good understanding of the Neo4j GraphQL Library first. 
Walk through the xref::getting-started/index.adoc[Getting started] guide or take the course https://graphacademy.neo4j.com/courses/graphql-basics/?ref=docs[Introduction to Neo4j & GraphQL] in GraphAcademy for more instructions.
====
