[[ogm]]
:description: This section describes how to use the OGM functionality in Neo4j GraphQL.
= OGM

Most applications don't only expose a single GraphQL API -- there may also be scheduled jobs, authentication, and migrations keeping an application on.
The OGM (Object Graph Mapper) can be used to programmatically interact with your Neo4j GraphQL API, so you can achieve these goals.

This section includes:

* xref::ogm/installation.adoc[Installation] - How to install the OGM.
* xref::ogm/examples.adoc[Examples] - Examples of how to use the OGM in Neo4j GraphQL.
* xref::ogm/private.adoc[`@private` directive] - How to use the `@private` directive
* xref::ogm/selection-set.adoc[Selection Set]
- xref::ogm/type-generation.adoc[TypeScript Type Generation]
- xref::ogm/reference.adoc[API Reference]

[NOTE]
Before diving into the OGM, it's recommended that you have a good understanding of the Neo4j GraphQL Library first. 
Walk through the xref::getting-started/index.adoc[Getting started] guide or take the course https://graphacademy.neo4j.com/courses/graphql-basics/?ref=docs[Introduction to Neo4j & GraphQL] in GraphAcademy for more instructions.
