[[ogm-api-reference]]
:description: This page is a reference guide to all functionalities in OGM.
= API Reference
:page-aliases: ogm/api-reference/model/aggregate.adoc, ogm/api-reference/model/create.adoc, \
ogm/api-reference/model/find.adoc, ogm/api-reference/model/delete.adoc, \
ogm/api-reference/model/update.adoc, ogm/api-reference/model/index.adoc, \
ogm/api-reference/index.adoc, ogm/api-reference/ogm.adoc, ogm/api-reference/type-generation.adoc

The following sections work as a reference guide to all functionalities in OGM and in the Model class.

== `OGM`

[cols="1,2,2"]
|===
|Function|Description|Example

|`constructor`
|Returns an `OGM` instance.
Takes an `input` object as a parameter, which is then passed to the `Neo4jGraphQL` constructor. Supported options are listed in the documentation for xref::reference/api-reference/neo4jgraphql.adoc[`Neo4jGraphQL`].
a|
[source, javascript, indent=0]
----
const ogm = new OGM({
    typeDefs,
});
----

|`init`
|Asynchronous method to initialize the OGM. 
Internally, calls xref::reference/api-reference/neo4jgraphql.adoc#api-reference-getschema[`Neo4jGraphQL.getSchema()`] to generate a GraphQL schema, and stores the result. 
Initializes any models which have been created before this execution, and will throw an error if any of them are invalid.
a|
[source, javascript, indent=0]
----
await ogm.init();
----

|`model`
|Returns a `model` instance matching the passed in name, or (if the OGM has been initialized) throws an `Error` if one can't be found.
Accepts a single argument `name` of type `string`.
a|
.Type definition
[source, graphql, indent=0]
----
type User {
    username: String!
}
----

.Query return
[source, javascript, indent=0]
----
const User = ogm.model("User");
----

.Wrong query
[source, javascript, indent=0]
----
const User = ogm.model("NotFound");
----

|`generate`
|Either writes to specified `outFile` or returns a string - if `noWrite` is set. 
a|
.Writing to outFile
[source, typescript, indent=0]
----
import { OGM, generate } from "@neo4j/graphql-ogm";

const typeDefs = `
    type Movie {
        id: ID
        name: String
    }
`;

const driver = neo4j.driver(
    "bolt://localhost:7687",
    neo4j.auth.basic("admin", "password")
);

const ogm = new OGM({ typeDefs, driver });

await generate({
    ogm,
    outFile: "path/to/my/file.ts",
});

console.log("Types Generated");
----

.Writing with noWrite
[source, typescript, indent=0]
----
import { OGM, generate } from "@neo4j/graphql-ogm";

const typeDefs = `
    type Movie {
        id: ID
        name: String
    }
`;

const driver = neo4j.driver(
    "bolt://localhost:7687",
    neo4j.auth.basic("admin", "password")
);

const ogm = new OGM({ typeDefs, driver });

const source = await generate({
    ogm,
    noWrite: true,
});

console.log("Types Generated ", source);
----
|===

[discrete]
=== `assertIndexesAndConstraints`

Asynchronous method to assert the existence of database constraints, that either resolves to `void` in a successful scenario, or throws an error if the necessary constraints do not exist following its execution.
It takes an `input` object as a parameter, being the supported fields the following examples.

Given the type definitions saved to the variable `typeDefs` and a valid driver instance saved to the variable `driver`:

[source, graphql, indent=0]
----
type Book {
    isbn: String! @unique
}
----

And the construction and initialization of an `OGM`, using:

[source, javascript, indent=0]
----
const ogm = new OGM({
    typeDefs,
});
await ogm.init();
----

The following checks whether a unique node property constraint exists for label "Book" and property "isbn", and throws an error if it does not:

[source, javascript, indent=0]
----
await ogm.assertIndexesAndConstraints();
----

The next example creates the constraint if it does not exist:

[source, javascript, indent=0]
----
await ogm.assertIndexesAndConstraints({ options: { create: true } });
----

[discrete]
==== Input

Accepts the argument:

[cols="1,2,3"]
|===
|Name |Type |Description

|`options`
|`AssertConstraintsOptions`
|Options for the execution of `assertIndexesAndConstraints`.
|===


[discrete]
==== `AssertConstraintsOptions`

[cols="1,2,3"]
|===
|Name |Type |Description

|`create`
|`boolean`
|Whether or not to create constraints if they do not yet exist. Disabled by default.
|===


[[ogm-model]]
== Model

[[ogm-api-reference-model-aggregate]]
=== `aggregate`

This method can be used to aggregate nodes, and maps to the underlying schema xref::queries-aggregations/queries.adoc#queries-aggregate[Aggregate].

==== Arguments

[cols="1,2,2"]
|===
|Name|Type|Description

|`where`
|`GraphQLWhereArg`
|A JavaScript object representation of the GraphQL `where` input type used for xref::queries-aggregations/filtering.adoc[Filtering].
|===

==== Example

Here is how you can write a query to find the longest User name:

[source, javascript, indent=0]
----
const User = ogm.model("User");

const usersAggregate = await User.aggregate({
    aggregate: {
        name: {
            longest: true
        }
    }
});
----

And this one is to find the longest User name where name starts with the letter "D":

[source, javascript, indent=0]
----
const User = ogm.model("User");

const usersAggregate = await User.aggregate({
    where: {
        name_STARTS_WITH: "D"
    },
    aggregate: {
        name: {
            longest: true
        }
    }
});
----


[[ogm-api-reference-model-create]]
=== `create`

This method can be used to update nodes, and maps to the underlying xref::mutations/create.adoc[`create`] Mutation.
It returns a `Promise` that resolves to the equivalent of the Mutation response for this operation.

==== Arguments

[cols="1,2,2"]
|===
|Name|Type |Description

|`input`
|`any`
|JavaScript object representation of the GraphQL `input` input type used for xref::mutations/create.adoc[Create] mutations.

|`selectionSet`
|`string` or `DocumentNode` or `SelectionSetNode`
|Selection set for the Mutation, see xref::ogm/selection-set.adoc[Selection Set] for more information.

|`args`
|`any`
|The `args` value for the GraphQL Mutation.

|`context`
|`any`
|The `context` value for the GraphQL Mutation.

|`rootValue`
|`any`
|The `rootValue` value for the GraphQL Mutation.
|===

==== Example

Here is an example on how to create a Movie with title "The Matrix":

[source, javascript, indent=0]
----
const Movie = ogm.model("Movie");

await Movie.create({ input: [{ title: "The Matrix" }] })
----

[[ogm-api-reference-model-delete]]
=== `delete`

This method can be used to delete nodes, and maps to the underlying xref::mutations/delete.adoc[Delete] Mutation.
It returns a `Promise` which resolvers to a `DeleteInfo` object:

[cols="1,1,1"]
|===
|Name|Type |Description

|`nodesDeleted`
|`number`
|The number of nodes deleted.

|`relationshipsDeleted`
|`number`
|The number of relationships deleted.
|===

==== Arguments

[cols="1,2,2"]
|===
|Name|Type |Description

|`where`
|`GraphQLWhereArg`
|A JavaScript object representation of the GraphQL `where` input type used for xref::queries-aggregations/filtering.adoc[Filtering].

|`delete`
|`string` or `DocumentNode` or `SelectionSetNode`
|A JavaScript object representation of the GraphQL `delete` input type used for xref::mutations/delete.adoc[`delete`] mutations.

|`context`
|`any`
|The `context` value for the GraphQL mutation.

|`rootValue`
|`any`
|The `rootValue` value for the GraphQL mutation.
|===

==== Example

This is how you can delete all User nodes where the name is "Dan":

[source, javascript, indent=0]
----
const User = ogm.model("User");

await User.delete({ where: { name: "Dan" }});
----

[[ogm-api-reference-model-find]]
=== `find`

This method can be used to find nodes, and maps to the underlying schema xref::queries-aggregations/queries.adoc[Queries].
It returns a `Promise` which resolvers to an array of objects matching the type of the Model.

==== Arguments

[cols="1,2,2"]
|===
|Name|Type |Description

|`where`
|`GraphQLWhereArg`
|A JavaScript object representation of the GraphQL `where` input type used for xref::queries-aggregations/filtering.adoc[Filtering].

|`options`
|`GraphQLOptionsArg`
|A JavaScript object representation of the GraphQL `options` input type used for xref::queries-aggregations/sorting.adoc[Sorting] and xref::/queries-aggregations/pagination/index.adoc[Pagination].

|`selectionSet` 
|`string` or `DocumentNode` or `SelectionSetNode`
|Selection set for the Mutation, see xref::ogm/selection-set.adoc[Selection Set] for more information.

|`args`
|`any`
|The `args` value for the GraphQL Mutation.

|`context`
|`any`
|The `context` value for the GraphQL Mutation.

|`rootValue`
|`any`
|The `rootValue` value for the GraphQL Mutation.
|===

==== Example

Here is how to find all user nodes in the database:

[source, javascript, indent=0]
----
const User = ogm.model("User");

const users = await User.find();
----

In case you want to find users with name "Jane Smith", here is how to do it:

[source, javascript, indent=0]
----
const User = ogm.model("User");

const users = await User.find({ where: { name: "Jane Smith" }});
----

[[ogm-api-reference-model-update]]
=== `update`

This method can be used to update nodes, and maps to the underlying xref::mutations/update.adoc[`update`] mutation.
It returns a `Promise` that resolves to the equivalent of the mutation response for this operation.


==== Arguments

[cols="1,2,2"]
|===
|Name|Type |Description

|`where`
|`GraphQLWhereArg`
|A JavaScript object representation of the GraphQL `where` input type used for xref::queries-aggregations/filtering.adoc[Filtering].

|`update`
|`any`
|A JavaScript object representation of the GraphQL `update` input type used for xref::mutations/update.adoc[`update`] Mutations.

|`connect`
|`any`
|A JavaScript object representation of the GraphQL `connect` input type used for xref::mutations/update.adoc[`update`] Mutations.

|`disconnect`
|`any`
|A JavaScript object representation of the GraphQL `disconnect` input type used for xref::mutations/update.adoc[`update`] Mutations.

|`create`
|`any`
|A JavaScript object representation of the GraphQL `create` input type used for xref::mutations/update.adoc[`update`] Mutations.

|`options`
|`GraphQLOptionsArg`
|A JavaScript object representation of the GraphQL `options` input type used for xref::queries-aggregations/sorting.adoc[Sorting] and xref::/queries-aggregations/pagination/index.adoc[Pagination].

|`selectionSet`
|`string` or `DocumentNode` or `SelectionSetNode`
|Selection set for the Mutation, see xref::ogm/selection-set.adoc[Selection set] for more information.

|`args`
|`any`
|The `args` value for the GraphQL Mutation.

|`context`
|`any`
|The `context` value for the GraphQL Mutation.

|`rootValue`
|`any`
|The `rootValue` value for the GraphQL Mutation.
|===

==== Example

Here is how to update the User with name "John" to be "Jane":

[source, javascript, indent=0]
----
const User = ogm.model("User");

const { users } = await User.update({
    where: { name: "John" },
    update: { name: "Jane" },
});
----