[[ogm-api-reference]]
= API Reference
:page-aliases: ogm/api-reference/model/aggregate.adoc, ogm/api-reference/model/create.adoc, \
ogm/api-reference/model/find.adoc, ogm/api-reference/model/delete.adoc, \
ogm/api-reference/model/update.adoc, ogm/api-reference/model/index.adoc, \
ogm/api-reference/index.adoc, ogm/api-reference/ogm.adoc, ogm/api-reference/type-generation.adoc

== `OGM`

=== `constructor`

Returns an `OGM` instance.

Takes an `input` object as a parameter, which is then passed to the `Neo4jGraphQL` constructor. Supported options are listed in the documentation for xref::reference/api-reference/neo4jgraphql.adoc[`Neo4jGraphQL`].

==== Example

[source, javascript, indent=0]
----
const ogm = new OGM({
    typeDefs,
});
----

=== `init`

Asynchronous method to initialize the OGM. Internally, calls xref::reference/api-reference/neo4jgraphql.adoc#api-reference-getschema[`Neo4jGraphQL.getSchema()`] to generate a GraphQL schema, and stores the result. Initializes any models which have been created before this execution, and will throw an error if any of them are invalid.

=== `model`

Returns a `Model` instance matching the passed in name, or (if the OGM has been initialized) throws an `Error` if one can't be found.

Accepts a single argument `name` of type `string`.

==== Example

For the following type definitions:

[source, javascript, indent=0]
----
type User {
    username: String!
}
----

The following would successfully return a `Model` instance:

[source, javascript, indent=0]
----
const User = ogm.model("User");
----

The following would throw an `Error`:

[source, javascript, indent=0]
----
const User = ogm.model("NotFound");
----

[[ogm-api-type-generation]]
=== `generate`

Either writes to specified `outFile` or returns a string - if `noWrite` is set. 

==== Example with outFile

Will write to outFile:

[source, typescript, indent=0]
----
import { OGM, generate } from "@neo4j/graphql-ogm";

const typeDefs = `
    type Movie {
        id: ID
        name: String
    }
`;

const driver = neo4j.driver(
    "bolt://localhost:7687",
    neo4j.auth.basic("admin", "password")
);

const ogm = new OGM({ typeDefs, driver });

await generate({
    ogm,
    outFile: "path/to/my/file.ts",
});

console.log("Types Generated");
----

==== Example with noWrite

Will return a string:

[source, typescript, indent=0]
----
import { OGM, generate } from "@neo4j/graphql-ogm";

const typeDefs = `
    type Movie {
        id: ID
        name: String
    }
`;

const driver = neo4j.driver(
    "bolt://localhost:7687",
    neo4j.auth.basic("admin", "password")
);

const ogm = new OGM({ typeDefs, driver });

const source = await generate({
    ogm,
    noWrite: true,
});

console.log("Types Generated ", source);
----


[[ogm-api-reference-assertconstraints]]
=== `assertIndexesAndConstraints`

Asynchronous method to assert the existence of database constraints, that either resolves to `void` in a successful scenario, or throws an error if the necessary constraints do not exist following its execution.

Takes an `input` object as a parameter, the supported fields of which are described below.

==== Example

Given the following type definitions saved to the variable `typeDefs` and a valid driver instance saved to the variable `driver`:

[source, graphql, indent=0]
----
type Book {
    isbn: String! @unique
}
----

And the construction and initialisation of an `OGM`, using:

[source, javascript, indent=0]
----
const ogm = new OGM({
    typeDefs,
});
await ogm.init();
----

The following will check whether a unique node property constraint exists for label "Book" and property "isbn", and throw an error if it does not:

[source, javascript, indent=0]
----
await ogm.assertIndexesAndConstraints();
----

The next example will create the constraint if it does not exist:

[source, javascript, indent=0]
----
await ogm.assertIndexesAndConstraints({ options: { create: true } });
----

[[ogm-api-reference-assertconstraints-input]]
==== Input

Accepts the arguments below:

[cols="1,2,3"]
|===
|Name |Type |Description

|`options`
|xref::ogm/reference.adoc#ogm-api-reference-assertconstraints-input-assertconstraintsoptions[`AssertConstraintsOptions`]
|Options for the execution of `assertIndexesAndConstraints`.
|===


[[ogm-api-reference-assertconstraints-input-assertconstraintsoptions]]
===== `AssertConstraintsOptions`

[cols="1,2,3"]
|===
|Name |Type |Description

|`create`
|`boolean`
|Whether or not to create constraints if they do not yet exist. Disabled by default.
|===

[[ogm-model]]
== Model

[[ogm-api-reference-model-aggregate]]
=== `aggregate`

This method can be used to aggregate nodes, and maps to the underlying schema xref::queries-aggregations/queries.adoc#queries-aggregate[Aggregate].

==== Example

Find the longest User name:

[source, javascript, indent=0]
----
const User = ogm.model("User");

const usersAggregate = await User.aggregate({
    aggregate: {
        name: {
            longest: true
        }
    }
});
----

Find the longest User name where name starts with the letter "D":

[source, javascript, indent=0]
----
const User = ogm.model("User");

const usersAggregate = await User.aggregate({
    where: {
        name_STARTS_WITH: "D"
    },
    aggregate: {
        name: {
            longest: true
        }
    }
});
----

==== Arguments

|===
|Name and Type |Description

|`where` +
 +
 Type: `GraphQLWhereArg`
|A JavaScript object representation of the GraphQL `where` input type used for xref::queries-aggregations/filtering.adoc[Filtering].
|===

[[ogm-api-reference-model-create]]
=== `create`

This method can be used to update nodes, and maps to the underlying xref::mutations/create.adoc[Create] Mutation.

Returns a `Promise` that resolves to the equivalent of the Mutation response for this operation.

==== Example

To create a Movie with title "The Matrix":

[source, javascript, indent=0]
----
const Movie = ogm.model("Movie");

await Movie.create({ input: [{ title: "The Matrix" }] })
----

==== Arguments

|===
|Name and Type |Description

|`input` +
 +
 Type: `any`
|JavaScript object representation of the GraphQL `input` input type used for xref::mutations/create.adoc[Create] mutations.

|`selectionSet` +
 +
 Type: `string` or `DocumentNode` or `SelectionSetNode`
|Selection set for the Mutation, see xref::ogm/selection-set.adoc[Selection Set] for more information.

|`args` +
 +
 Type: `any`
|The `args` value for the GraphQL Mutation.

|`context` +
 +
 Type: `any`
|The `context` value for the GraphQL Mutation.

|`rootValue` +
 +
 Type: `any`
|The `rootValue` value for the GraphQL Mutation.
|===

[[ogm-api-reference-model-delete]]
=== `delete`

This method can be used to delete nodes, and maps to the underlying xref::mutations/delete.adoc[Delete] Mutation.

Returns a `Promise` which resolvers to a `DeleteInfo` object:

|===
|Name and Type |Description

|`nodesDeleted` +
 +
 Type: `number`
|The number of nodes deleted.

|`relationshipsDeleted` +
 +
 Type: `number`
|The number of relationships deleted.
|===

==== Example

To delete all User nodes where the name is "Dan":

[source, javascript, indent=0]
----
const User = ogm.model("User");

await User.delete({ where: { name: "Dan" }});
----

==== Arguments

|===
|Name and Type |Description

|`where` +
 +
 Type: `GraphQLWhereArg`
|A JavaScript object representation of the GraphQL `where` input type used for xref::queries-aggregations/filtering.adoc[Filtering].

|`delete` +
 +
 Type: `string` or `DocumentNode` or `SelectionSetNode`
|A JavaScript object representation of the GraphQL `delete` input type used for xref::mutations/delete.adoc[Delete] Mutations.

|`context` +
 +
 Type: `any`
|The `context` value for the GraphQL Mutation.

|`rootValue` +
 +
 Type: `any`
|The `rootValue` value for the GraphQL Mutation.
|===

[[ogm-api-reference-model-find]]
=== `find`

This method can be used to find nodes, and maps to the underlying schema xref::queries-aggregations/queries.adoc[Queries].

Returns a `Promise` which resolvers to an array of objects matching the type of the Model.

==== Example

To find all user nodes in the database:

[source, javascript, indent=0]
----
const User = ogm.model("User");

const users = await User.find();
----

To find users with name "Jane Smith":

[source, javascript, indent=0]
----
const User = ogm.model("User");

const users = await User.find({ where: { name: "Jane Smith" }});
----

==== Arguments

|===
|Name and Type |Description

|`where` +
 +
 Type: `GraphQLWhereArg`
|A JavaScript object representation of the GraphQL `where` input type used for xref::queries-aggregations/filtering.adoc[Filtering].

|`options` +
 +
 Type: `GraphQLOptionsArg`
|A JavaScript object representation of the GraphQL `options` input type used for xref::queries-aggregations/sorting.adoc[Sorting] and xref::/queries-aggregations/pagination/index.adoc[Pagination].

|`selectionSet` +
 +
 Type: `string` or `DocumentNode` or `SelectionSetNode`
|Selection set for the Mutation, see xref::ogm/selection-set.adoc[Selection Set] for more information.

|`args` +
 +
 Type: `any`
|The `args` value for the GraphQL Mutation.

|`context` +
 +
 Type: `any`
|The `context` value for the GraphQL Mutation.

|`rootValue` +
 +
 Type: `any`
|The `rootValue` value for the GraphQL Mutation.
|===

[[ogm-api-reference-model-update]]
=== `update`

This method can be used to update nodes, and maps to the underlying xref::mutations/update.adoc[Update] Mutation.

Returns a `Promise` that resolves to the equivalent of the Mutation response for this operation.

==== Example

For the User with name "John", update their name to be "Jane":

[source, javascript, indent=0]
----
const User = ogm.model("User");

const { users } = await User.update({
    where: { name: "John" },
    update: { name: "Jane" },
});
----

==== Arguments

[cols="2,2,3,3"]
|===
|Name | Type | Description | Example

|`where`
|`GraphQLWhereArg`
|A JavaScript object representation of the GraphQL `where` input type used for xref::queries-aggregations/filtering.adoc[Filtering].
.5+a|
.Type definitions
[source, graphql, indent=0]
----
type Post {
    id: ID! @id
    content: String!
    creator: User! @relationship(type: "HAS_POST", direction: IN)
}

type User {
    id: ID! @id
    name: String
    posts: [Post!]! @relationship(type: "HAS_POST", direction: OUT)
}
----
.Query
[source, graphql, indent=0]
----
type UpdatePostsMutationResponse {
    posts: [Post!]!
}

type UpdateUsersMutationResponse {
    users: [User!]!
}

type Mutation {
    updatePosts(
        where: PostWhere
        update: PostUpdateInput
        connect: PostConnectInput
        disconnect: PostDisconnectInput
        create: PostCreateInput
        delete: PostDeleteInput
    ): UpdatePostsMutationResponse!
    updateUsers(
        where: UserWhere
        update: UserUpdateInput
        connect: UserConnectInput
        disconnect: UserDisconnectInput
        create: UserCreateInput
        delete: UserDeleteInput
    ): UpdateUsersMutationResponse!
}
----

|`update`
|`any`
|A JavaScript object representation of the GraphQL `update` input type used for xref::mutations/update.adoc[Update] mutations.

|`connect`
|`any`
|A JavaScript object representation of the GraphQL `connect` input type used for xref::mutations/update.adoc[Update] mutations.

|`disconnect`
|`any`
|A JavaScript object representation of the GraphQL `disconnect` input type used for xref::mutations/update.adoc[Update] mutations.

|`create`
|`any`
|A JavaScript object representation of the GraphQL `create` input type used for xref::mutations/update.adoc[Update] mutations.

|`options`
|`GraphQLOptionsArg`
|A JavaScript object representation of the GraphQL `options` input type used for xref::queries-aggregations/sorting.adoc[Sorting] and xref::/queries-aggregations/pagination/index.adoc[Pagination].
a|
[source, graphql, indent=0]
----
query {
    movies {
        title
        runtime
        actors(options: {
            sort: [
                {
                    surname: ASC
                }
            ]
        }) {
            surname
        }
    }
}
----

|`selectionSet`
|`string` or `DocumentNode` or `SelectionSetNode`
|Selection set for the mutation, see xref::ogm/selection-set.adoc[Selection set] for more information.
a|
.Type definition
[source, graphql, indent=0]
----
type Movie {
    id: ID
    name: String
    genres: [Genre!]! @relationship(type: "IN_GENRE", direction: OUT)
    customCypher: String! @cypher(statement: "RETURN someCustomData")
}

type Genre {
    name: String
}
----
.Query
[source, graphql, indent=0]
----
const { OGM } = require("@neo4j/graphql-ogm")
const neo4j = require("neo4j-driver");

const driver = neo4j.driver(
    "bolt://localhost:7687",
    neo4j.auth.basic("admin", "password")
);

const typeDefs = `
    type Movie {
        id: ID
        name: String
        genres: [Genre!]! @relationship(type: "IN_GENRE", direction: OUT)
        customCypher: String! @cypher(statement: "RETURN someCustomData")
    }

    type Genre {
        name: String
    }
`;

const ogm = new OGM({ typeDefs, driver });
const Movie = ogm.model("Movie");

const selectionSet = `
    {
        id
        name
        genres {
            name
        }
        customCypher
    }
`;

ogm.init().then(() => {
    Movie.find({ selectionSet }).then((movies) => {
        // work with movies
    })
});
----

|`args`
|`any`
|The `args` value for the GraphQL mutation.
a|
[source, graphql, indent=0]
----
query GetUsersByAge($minAge: Int!, $maxAge: Int!) {
  users(where: { age: { gte: $minAge, lte: $maxAge } }) {
    name
    age
  }
}
----

|`context`
|`any`
|The `context` value for the GraphQL Mutation.
a|
[source, javascript, indent=0]
----
const { ApolloServer, gql } = require('apollo-server');

// Sample data
const users = [
  { id: 'user-id-here', name: 'Old Name' },
  // Other user data...
];

const typeDefs = gql`
  type User {
    id: ID!
    name: String!
  }

  type Mutation {
    updateUser(id: ID!, newName: String!): User
  }
`;

const resolvers = {
  Mutation: {
    updateUser: (_, { id, newName }, context) => {
      // Find the user by ID in the sample data (you would replace this with your database logic)
      const userIndex = users.findIndex(user => user.id === id);

      if (userIndex === -1) {
        throw new Error('User not found');
      }

      // Update the user's name
      users[userIndex].name = newName;

      // Return the updated user
      return users[userIndex];
    },
  },
};

const server = new ApolloServer({
  typeDefs,
  resolvers,
  context: { /* You can provide context data here */ },
});

server.listen().then(({ url }) => {
  console.log(`Server ready at ${url}`);
});

----

|`rootValue`
|`any`
|The `rootValue` value for the GraphQL Mutation.
a|
[source, javascript, indent=0]
----
const { ApolloServer, gql } = require('apollo-server');

// Sample data
let users = [
  { id: '1', name: 'John' },
  { id: '2', name: 'Jane' },
];

// GraphQL schema definition
const typeDefs = gql`
  type User {
    id: ID!
    name: String!
  }

  type Mutation {
    updateUser(id: ID!, newName: String!): User
  }

  type Query {
    user(id: ID!): User
  }
`;

// Resolver functions
const resolvers = {
  Query: {
    user: (_, { id }) => users.find(user => user.id === id),
  },
  Mutation: {
    updateUser: (_, { id, newName }, { rootValue }) => {
      // In this simplified example, we update the user's name in the local data
      const user = users.find(user => user.id === id);
      if (!user) {
        throw new Error('User not found');
      }

      user.name = newName;

      // Return the updated user
      return user;
    },
  },
};

// Create Apollo Server
const server = new ApolloServer({
  typeDefs,
  resolvers,
  context: { rootValue: 'Some contextual data or services' }, // You can provide rootValue here
});

// Start the server
server.listen().then(({ url }) => {
  console.log(`Server ready at ${url}`);
});

----
|===
