[[schema-configuration-type-configuration]]
= Type Configuration

When representing a Neo4j Node, a GraphQL Object type produces multiple operation fields in the `Query`, `Mutation`, and `Subscription` types. 
For example:

[source, graphql, indent=0]
----
type Movie { 
    title: String 
    length: Int
}
----

From these type definitions, the library generates the following operation fields:

**Query**:

    * `movies`
    * `moviesAggregate`
    * `moviesConnection`

**Mutation**:

    * `createMovies`
    * `deleteMovies`
    * `updateMovies`

**Subscription**:

    * `movieCreated`
    * `movieUpdated`
    * `movieDeleted`
.

This section explains how to reduce the operation fields produced using the directives `@query`, `@mutation`, and `@subscription`.

== `@query`

This directive is used to limit the availability of query operations in the library.

=== Definition

[source, graphql, indent=0]
----
directive @query(read: Boolean! = true, aggregate: Boolean! = false) on OBJECT | SCHEMA
----

[NOTE]
====
Aggregations will no longer be generated by default in the 4.0.0 version of the library. 
See xref:migration/v4-migration/index.adoc#opt-in-aggregation[`Opt-in Aggregation`] for more information.
====

=== Usage

==== Disable _movies_ and _moviesConnection_ operations

[source, graphql, indent=0]
----
type Movie @query(read: false, aggregate: true) { 
    title: String 
    length: Int
}
----

==== Disable _moviesAggregate_ operations

[source, graphql, indent=0]
----
type Movie @query(read: true, aggregate: false)  { 
    title: String 
    length: Int
}
----

== `@mutation`

This directive is used to limit the availability of Mutation operations in the library.

=== Definition

[source, graphql, indent=0]
----
enum MutationFields {
    CREATE
    UPDATE
    DELETE
}

directive @mutation(operations: [MutationFields!]! = [CREATE, UPDATE, DELETE]) on OBJECT | SCHEMA
----

=== Usage

==== Disable Create, Delete, and Update operations for _Movie_

[source, graphql, indent=0]
----
type Movie @mutation(operations: []) { 
    title: String 
    length: Int
}
----

==== Enable only Create operations for _Movie_

[source, graphql, indent=0]
----
type Movie @mutation(operations: [CREATE]) { 
    title: String 
    length: Int
}
----

== `@subscription`

This directive is used to limit Subscription operations in the library.

=== Definition

[source, graphql, indent=0]
----
enum SubscriptionFields {
    CREATE
    UPDATE
    DELETE
    CREATE_RELATIONSHIP
    DELETE_RELATIONSHIP
}

directive @subscription(operations: [SubscriptionFields!]! = [CREATE, UPDATE, DELETE, CREATE_RELATIONSHIP, DELETE_RELATIONSHIP]) on OBJECT | SCHEMA
----

=== Usage

==== Disable subscriptions for _Movie_

[source, graphql, indent=0]
----
type Movie @subscription(operations: [])  { 
    title: String 
    length: Int
}
----

==== Enable only _movieCreated_ subscription for _Movie_

[source, graphql, indent=0]
----
type Movie @subscription(operations: [CREATE]) { 
    title: String 
    length: Int
}
----