[[v6-migration]]
:description: This page lists the breaking changes from version 5.0.0 to 6.0.0 and describes how to update.
:page-aliases: guides/index.adoc, guides/migration-guide/index.adoc, guides/migration-guide/server.adoc, \
guides/migration-guide/queries.adoc, guides/migration-guide/type-definitions.adoc, guides/migration-guide/mutations.adoc

= Migration to 6.0.0

This page lists all breaking changes from the Neo4j GraphQL Library version 5.x to 6.x and how to update it.

== How to update

To update your Neo4j GraphQL Library, use npm or the package manager of choice:

[source, bash, indent=0]
----
npm update @neo4j/graphql
----

== Breaking changes

Here is a list of all the breaking changes from version 5.0.0 to 6.0.0.

=== The deprecated `_NOT` filters are no longer supported

The following deprecated `NOT` filters are removed from the schema since they are no longer supported:

  - `_NOT`
  - `_NOT_CONTAINS`
  - `_NOT_ENDS_WITH`
  - `_NOT_IN`
  - `_NOT_STARTS_WITH`
  - `_NOT_INCUDES`
  - `node_NOT`
  - `edge_NOT`


To achieve the same in version 6.x of the GraphQL library, use the xref:/queries-aggregations/filtering.adoc#_boolean_operators[boolean `NOT` operator] instead.

[cols="1,1"]
|===
|Before | Now

a|
[source, graphql, indent=0]
----
query {
  movies(where: { title_NOT: "The Matrix" }) {
    title
  }
}

----
a|
[source, graphql, indent=0]
----
query {
  movies(where: { NOT: { title: "The Matrix" } }) {
    title
  }
}
----
|===

=== The deprecated `_NOT` on `@relationship` filters are no longer supported

The deprecated `_NOT` filters on `@relationship` fields such as:

  - `actors_NOT`
  - `actorsConnection_NOT`

Are removed from the schema and no longer supported, to achieve the same result use the `NONE` quantifier.

[cols="1,1"]
|===
|Before | Now

a|
[source, graphql, indent=0]
----
query {
  movies(where: { actors_NOT: { name: "Keanu" } }) {
    title
  }
}
----
a|
[source, graphql, indent=0]
----
query {
  movies(where: { actors_NONE: { name: "Keanu" } }) {
    title
  }
}
----
|===

== Deprecations and warnings

=== Implicit equality filters are deprecated

Implicit equality filters such as: 

  - `{ name: "Keanu" }`
  - `{ count: 10 }` 

Are deprecated in favor of `{ name_EQ: "Keanu" }` and `{ count_EQ: 10 }` respectively and will be removed in the next major version.

[cols="1,1"]
|===
|Before | Now

a|
[source, graphql, indent=0]
----
query {
  users(where: { name: "John" }) {
    id
    name
  }
}
----
a|
[source, graphql, indent=0]
----
query {
  users(where: { name_EQ: "John" }) {
    id
    name
  }
}
----
|===


=== `@node` will have to be explicitly defined

In the future, types without the `@node` directive will no longer be treated as Neo4j nodes.
In version 6.0.0, it's not required to specify every GraphQL type representing a Neo4j node with the `@node` directive, however it's recommended to do so and a warning is raised if you don't.
There are genuine cases in which a `@node` should not be used, e.g., for types returned by @cypher fields which are not Neo4j nodes.

[cols="1,1"]
|===
|Before | Now

a|
[source, graphql, indent=0]
----
type Movie {
    title: String
    actors: [Person!]! @relationship(type: "ACTED_IN", direction: IN)
}

type Person {
    name: String
}
----
a|
[source, graphql, indent=0]
----
type Movie @node {
    title: String
    actors: [Person!]! @relationship(type: "ACTED_IN", direction: IN)
}

type Person @node {
    name: String
}
----
|===

