[[v6-migration]]
:description: This page lists the breaking changes from version 5.0.0 to 6.0.0 and describes how to update.
:page-aliases: guides/index.adoc, guides/migration-guide/index.adoc, guides/migration-guide/server.adoc, \
guides/migration-guide/queries.adoc, guides/migration-guide/type-definitions.adoc, guides/migration-guide/mutations.adoc

= Migration to 6.0.0

This page lists all breaking changes from the Neo4j GraphQL Library version 5.x to 6.x and how to update it.

== How to update

To update your Neo4j GraphQL Library, use npm or the package manager of choice:

[source, bash, indent=0]
----
npm update @neo4j/graphql
----

== Breaking changes

Here is a list of all the breaking changes from version 5.0.0 to 6.0.0.


== Deprecations and Warnings

=== `@node` will be required to be explicitly defined

In the future, types without the `@node` directive will no longer be treated as Neo4j nodes.
In version 6.0.0, it's not required to specify every GraphQL type representing a Neo4j node with the `@node` directive, however it's recommended to do so and a warning is raised if not found.
There are genuine cases in which a `@node` should not be used e.g., for type returned by @cypher fields which are not Neo4j nodes.

[cols="1,1"]
|===
|Before | Now

a|
[source, graphql, indent=0]
----
type Movie {
    title: String
    actors: [Person!]! @relationship(type: "ACTED_IN", direction: IN)
}

type Person {
    name: String
}
----
a|
[source, graphql, indent=0]
----
type Movie @node {
    title: String
    actors: [Person!]! @relationship(type: "ACTED_IN", direction: IN)
}

type Person @node {
    name: String
}
----
|===

