[[aggregations]]
:description: This page describes aggregations supported by Neo4j GraphQL.
= Aggregations

== Type definitions

Queries on this page assume the following type definitions:

[source, graphql, indent=0]
----
type Post @node {
    id: ID! @id
    content: String!
    creators: [User!]! @relationship(type: "HAS_POST", direction: IN, properties: "PostedAt")
    createdAt: DateTime!
}

type User @node {
    id: ID! @id
    name: String!
    age: Int!
    posts: [Post!]! @relationship(type: "HAS_POST", direction: OUT, properties: "PostedAt")
    friends: [User!]! @relationship(type: "FRIENDS_WITH", direction: OUT)
}

type PostedAt @relationshipProperties {
    date: DateTime
}
----

For which the following query fields are generated:

[source, graphql, indent=0]
----
type Query {
    posts(where: PostWhere, sort: [PostSort!]!, limit: Int, offset: Int,): [Post!]!
    postsConnection(after: String, first: Int, sort: [PostSort], where: PostWhere): PostsConnection!
    users(where: UserWhere, sort: [UserSort!]!, limit: Int, offset: Int,): [User!]!
    usersConnection(after: String, first: Int, sort: [UserSort], where: UserWhere): UsersConnection!
}
----

== Querying aggregations

Aggregations on a type are provided in the field `aggregate` inside Connection:

[source, graphql, indent=0]
----
query {
    usersConnection {
        aggregate {
            node {
                name {
                    longest
                }
            }
        }
    }
}
----



== Aggregation fields

Based on the type definitions, here is a list of fields that accept aggregations supported by Neo4j GraphQL:

[cols="1,1,2"]
|===
| Type | Aggregating function | Example

| String (e.g. `ID`, `String`)
| `shortest`, `longest`
a| 
.Longest User name
[source, graphql, indent=0]
----
query {
    usersConnection {
        aggregate {
            name {
                longest
            }
        }
    }
}
----


| Temporal (e.g. `DateTime`, `Time`, `LocalTime`, `LocalDateTime`, `Duration`)
| `min`, `max`
a|
.First Post date
[source, graphql, indent=0]
----
query {
    postsConnection {
        aggregate {
            node {
                createdAt {
                    min
                }
            }
        }
    }
}
----
|===


.Counting User nodes
[source, graphql, indent=0]
----
query {
    usersConnection {
        aggregate {
            count {
                nodes
            }
        }
    }
}
----

.Counting User nodes where name starts with "J"
[source, graphql, indent=0]
----
query {
    usersConnection(where: { name: { startsWith: "J" } }) {
        aggregate {
            count {
                nodes
            }
        }
    }
}
----


== Aggregating related nodes

You can aggregate related nodes in a query by accessing the aggregation fields in the connection.
In these fields, you can **count**, aggregate the **nodes** or **edges** fields.

The same selections and types as in xref:#_aggregation_fields[] are available in relationship aggregations.



.Counting all posts per User
[source, graphql, indent=0]
----
query {
    users {
        id
        postsConnection {
            aggregate {
                count {
                    nodes
                }
            }
        }
    }
}
----

By using the `node` field, related nodes properties can be aggregated:

.Finding longest post per User
[source, graphql, indent=0]
----
query {
    users {
        name
        postsConnection {
            aggregate {
                node {
                    content {
                        longest
                    }
                }
            }
        }
    }
}
----

== Aggregate relationships

Relationship properties can be aggregated as well by using the `edge` field:

.Counting edges between posts and users
[source, graphql, indent=0]
----
query {
    users {
        id
        postsConnection {
            aggregate {
                count {
                    edges
                }
            }
        }
    }
}
----

.Querying what User nodes posted up to a date
[source, graphql, indent=0]
----
query {
    users {
        name
        postsConnection {
            aggregate {
                edge {
                    date {
                        max
                    }
                }
            }
        }
    }
}
----


== A note about aggregate with pagination

Because aggregate is done within the `Connection` type, the optional arguments `first` and `after` are available for pagination. However, pagination **does not** apply to aggregate

For example:

[source, graphql, indent=0]
----
query {
    usersConnection(first: 10) {
        aggregate {
            count {
                nodes
            }
        }
    }
}
----

The result would return the count of all the nodes:

[source, json, indent=0]
----
{
    "usersConnection": {
        "aggregate": {
            "count": {
                "nodes": 38
            }
        }
    }
}
----


