[[queries]]
= Queries
:description: This page describes how to read or fetch values in the Neo4j GraphQL Library.

== Type definitions

Queries on this page assume the following type definitions:

[source, graphql, indent=0]
----
type Post @node {
    id: ID! @id
    content: String!
    creators: [User!]! @relationship(type: "HAS_POST", direction: IN, properties: "PostedAt")
    createdAt: DateTime!
}

type User @node {
    id: ID! @id
    name: String!
    age: Int!
    posts: [Post!]! @relationship(type: "HAS_POST", direction: OUT, properties: "PostedAt")
    friends: [User!]! @relationship(type: "FRIENDS_WITH", direction: OUT)
}

type PostedAt @relationshipProperties {
    date: DateTime
}
----

For which the following query fields are generated:

[source, graphql, indent=0]
----
type Query {
  postsConnection(first: Int, after: String, where: PostWhere, sort: [PostSort!]): PostsConnection!
  posts(where: PostWhere, limit: Int, offset: Int, sort: [PostSort!]): [Post!]!
  usersConnection(first: Int, after: String, where: UserWhere, sort: [UserSort!]): UsersConnection!
  users(where: UserWhere, limit: Int, offset: Int, sort: [UserSort!]): [User!]!
}
----

== Writing queries

Based on the type definitions, here are two examples of how to write queries for reading or retrieving values:

.Return all User nodes from their ID and name
[source, graphql, indent=0]
----
query {
    users {
        id
        name
    }
}
----

.Query User with name "Jane Smith" and their posts
[source, graphql, indent=0]
----
query {
  users(where: { name: { eq: "Jane Smith" } }) {
    id
    name
    posts {
      content
    }
  }
}
----

== Relationships

=== `queryDirection`

All relationships have a direction.
However, when querying them, it is possible to perform xref::queries-aggregations/queries.adoc#_undirected_queries[undirected queries].
To set the default behavior of a relationship when it is queried, you can use the argument `queryDirection`:

[source, graphql, indent=0]
----
type Person @node {
    name: String!
    born: Int!
    actedInMovies: [Movie!]! @relationship(type: "ACTED_IN", direction: OUT, queryDirection: DEFAULT_DIRECTED)
}
----

`queryDirection` can have the following values:

* `DIRECTED`: only directed queries can be performed on this relationship.
* `UNDIRECTED`: only undirected queries can be performed on this relationship.

=== Fetching your data

Now that you have the `Movie` information in your database, you can query everything altogether as follows:

[source, graphql, indent=0]
----
query {
    movies(where: { title: { eq: "Forrest Gump" } }) {
        title
        released
        directors {
            name
            born
        }
        actorsConnection {
            edges {
                properties {
                    roles
                }
                node {
                    name
                    born
                }
            }
        }
    }
}
----

[NOTE]
====
The `@relationship` directive is a reference to Neo4j relationships, whereas when writing queries, the phrase `edge(s)` is used to be consistent with the general API language used by Relay.
====