:description: Directives related to generative AI in the Neo4j GraphQL Library.

[[type-definitions-genai]]
= Generative AI

With the GraphQL directives for generative AI you can query your database for vector indexes.
Queries are either performed by the vector index of a specific node or by a query phrase.

A query by vector index finds nodes with a vector embedding similar to that index, which is also referred to as nearest neighbor search.

In contrast, a query by phrase (a string of text) passes the phrase to the link:https://neo4j.com/docs/cypher-manual/current/genai-integrations/[Neo4j GenAI plugin] and the plugin generates a vector embedding for it.
This embedding is then compared to the node vector embeddings in the database and the result set.

[NOTE] 
.Prerequisites
==== 
* The node vector embeddings already exist
* The embeddings must have been created using the same model
* Queries by vector index cannot be performed across multiple labels
* Queries by phrase require credentials for the Neo4j GenAI plugin
====

== `@vector`

Use an existing vector embedding on a node in the database to perform a nearest neighbor search.

=== Definition

[source, graphql]
----
"""
Informs @neo4j/graphql that there is a vector index in the database which allows users to search by the index in the generated schema.
"""
directive @vector(indexes: [VectorInput]!) on OBJECT
----

`VectorInput` is defined as follows:

[source, graphql]
----
input VectorInput {
  name: String!
  dimension: Int!
  similarityFunction: 'cosine' | 'euclidean'
  property: String!
}
----

=== Usage

.Type definition
[source, graphql]
----
type Product @vector(
  name: "Interesting",
  dimension: 1536,
  similarityFunction: 'cosine'
  property: "embeddingPropertyName"
) {
  name: String!
  description: String!
}
----

Adding the vector directive to the `Product` type creates a top-level query named `productsInterestingVector`.
The name is a combination of the plural form of the type name, the index name, and `Vector`:

.Query schema
[source, graphql]
----
type Query {
    productsInterestingVector(text: String!, where: ProductScoreWhere, sort: [ProductVectorSort!], limit: Int, offset: Int): [ProductVectorResult!]!
    products(where: ProdcutOperationWhere): ProductOperation!
}
type ProductOperation {
    connection(first: Int, after: String, sort: [ProductConnectionSort!]): ProductConnection!
    aggregation: ProductAggregation!
}
type ProductConnection {
    pageInfo: PageInfo! # Required by relay
    edges: [ProductEdge!]! # Required by relay
}
type ProductEdge {
    cursor: String! # Required by relay
    node: Product! # Required by relay
    score: Float
}
type Product {
    name: String!
    description: String!
}
----

.Example query
[source, graphql]
----
query {
  productsInterestingVector(
    text: "This is the submitted text which is converted into a vector embedding by the GenAI plugin",
    where: { edges: { score: { gt: 0.5 } } }
    sort: [{ product: { name: ASC } }]
  ) {
    connection {
      edges {
        score
        node {
          name
        }
      }
    }
  }
}
----


== `@genAI`

Perform a query which utilizes the link:https://neo4j.com/docs/cypher-manual/current/genai-integrations/[Neo4j GenAI plugin] to create a vector embedding for a search phrase and then compares it to existing vector embeddings on nodes in the database.
Requires credentials for the plugin.

=== Definition

[source, graphql]
----
"""
Informs @neo4j/graphql that there is a vector index in the database which allows users to search by the index in the generated schema.
"""
directive @genAI(indexes: [genAiInput]!) on OBJECT
----

`genAiInput` is defined as follows:

[source, graphql]
----
input genAiInput {
  indexName: String!
  propertyName: String!
  provider: String!
}
----

=== Usage

.Type definition
[source, graphql]
----
type Product @genAI(
  indexName: "Interesting",
  propertyName: "embeddingPropertyName"
  provider: "OpenAI"
) {
  name: String!
  description: String!
}
----

.Query schema
[source, graphql]
----
?
----
====


.Example query
[source, graphql]
----
?
----
====
