[[type-definitions-database-mapping]]
= Database mapping
:page-aliases: type-definitions/database-mapping.adoc, type-definitions/basics.adoc, type-definitions/index.adoc, type-definitions/directives/database-mapping.adoc
:description: This page describes how to use directives for database mapping.


This page describes how to use directives for database mapping.
Each type in your GraphQL type definitions can be mapped to an entity in your Neo4j database, such as nodes, relationships, and relationship properties.


[[type-definitions-node]]
== `@node`

Adding the `@node` directive to your GraphQL type specifies that it represents a Neo4j node.
For example, to represent a Neo4j node with the label "Movie" and a single property "title" of type string:

[source, graphql, indent=0]
----
type Movie @node {
    title: String
}
----

[NOTE]
====
In version 6.x, it's not required to specify every GraphQL type representing a Neo4j node with the `@node` directive.
In the future, types without the `@node` directive will no longer be treated as Neo4j nodes.
====

When not differently specified, the GraphQL type name is used as a label for the represented Neo4j node. It's possible to explicitly define the Neo4j node labels by using the argument `labels`:

[discrete]
=== `labels`

This parameter defines the list of label to be used in Neo4j instead of the GraphQL type name:

[source, graphql, indent=0]
----
type Dog @node(labels: ["K9"]) {
    name: String!
}
----

This way, the following query:

[source, graphql, indent=0]
----
{
  dogs {
    name
  }
}
----

Generates the Cypher query:

[source, cypher, indent=0]
----
MATCH (this: K9)
RETURN this { .name } as name
----

If the GraphQL type name should still be used as a label, it needs to be specified as well:

[source, graphql, indent=0]
----
type Dog @node(labels: ["Dog", "K9"]) {
    name: String!
}
----

This way, the following query:

[source, graphql, indent=0]
----
{
  dogs {
    name
  }
}
----

Generates the Cypher query:

[source, cypher, indent=0]
----
MATCH (this:Dog:K9)
RETURN this { .name } as this
----

[NOTE]
====
Defining `labels` means you take control of the database labels of the node. 
Indexes and constraints in Neo4j only support a single label, for which the first element of the `labels` argument is used.
====

The following example results in a unique constraint to be asserted for the label `K9` and the property `name`:

[source, graphql, indent=0]
----
type Dog @node(labels: ["K9", "Dog"]) {
    name: String! @unique
}
----


[discrete]
=== Using `$jwt` and `$context`

In some cases, you may want to generate dynamic labels depending on the user requesting. 
For that, you can use the variable `$jwt` to define a custom label in the JWT:

[source, graphql, indent=0]
----
type User @node(labels: ["$jwt.username"]) {
    name: String!
}
----

The following query yields a different Cypher query depending on the user JWT:

[source, graphql, indent=0]
----
{
  users {
    name
  }
}
----

Assuming there is a user with the value `"username": "arthur"` in JWT, the Cypher query looks like:

[source, cypher, indent=0]
----
MATCH (this:arthur)
RETURN this { .name } as this
----

Similarly, context values can be passed directly:

[source, graphql, indent=0]
----
type User @node(label: ["$context.appId"]) {
    name: String!
}
----

When running the server with Apollo:

[source, js, indent=0]
----
const server = new ApolloServer({
    schema: await neoSchema.getSchema(),
});

await startStandaloneServer(server, {
    context: async ({ req }) => ({ req, appId: "myApp" }),
});
----

== `@relationship`

Relationships are represented by marking particular fields with a directive -- in this case, `@relationship`. 
It defines the relationship type in the database, as well as its direction.

The following type definitions add a second node type, `Actor`, and connect `Movie` and `Actor` via the `ACTED_IN` relationship:

[source, graphql, indent=0]
----
type Movie @node {
    title: String
    actors: [Actor!]! @relationship(type: "ACTED_IN", direction: IN)
}

type Actor @node {
    name: String
    movies: [Movie!]! @relationship(type: "ACTED_IN", direction: OUT)
}
----

Note that, in this case, there is a directive on each "end" of the relationship, but it is not essential.


== `@relationshipProperties`

=== Definition

[source, graphql, indent=0]
----
"""Required to differentiate between interfaces for relationship properties, and otherwise."""
directive @relationshipProperties on OBJECT
----

`@relationshipProperties` can only be used on interfaces.

=== Usage

In order to add properties to a relationship, add a new type to your type definitions decorated with the `@relationshipProperties` directive.

For example, for the "ACTED_IN" relationship, add a property "roles":

[source, graphql, indent=0]
----
type Movie @node {
    title: String
    actors: [Actor!]! @relationship(type: "ACTED_IN", direction: IN, properties: "ActedIn")
}

type Actor @node {
    name: String
    movies: [Movie!]! @relationship(type: "ACTED_IN", direction: OUT, properties: "ActedIn")
}

type ActedIn @relationshipProperties {
    roles: [String]
}
----

Note that in addition to this type, there is an added key `properties` in the existing `@relationship` directives.
For more information, see xref::/types/relationships.adoc[Type definitions -> Relationships].


[[type-definitions-alias]]
== `@alias`

This directive maps a GraphQL field to a Neo4j property on a node or relationship.
It can be used on any fields that are not `@cypher` or `@relationship` fields.

For example:

[source, graphql, indent=0]
----
type User @node {
    id: ID! @id @alias(property: "dbId")
    username: String!
}
----

[source, graphql, indent=0]
----
type User @node {
    id: ID! @id
    username: String! @alias(property: "dbUserName")
    livesIn: [City!]! @relationship(direction: OUT, type: "LIVES_IN", properties: "UserLivesInProperties")
}

type City @node {
    name: String
}

type UserLivesInProperties @relationshipProperties {
    since: DateTime @alias(property: "moveInDate")
}
----

[NOTE]
The property in aliases are automatically escaped (wrapped with backticks ``), so there is no need to add escape characters around them.
