[[type-definitions-database-mapping]]
= Database mapping
:page-aliases: type-definitions/database-mapping.adoc, type-definitions/basics.adoc, type-definitions/index.adoc, type-definitions/directives/database-mapping.adoc
:description: This page describes how to use directives for database mapping.


This page describes how to use directives for database mapping.
Each type in your GraphQL type definitions can be mapped to an entity in your Neo4j database, such as nodes, relationships, and relationship properties.


== `@relationship`

=== Definition

// tba

=== Usage

Relationships are represented by marking particular fields with a directive -- in this case, `@relationship`. 
It defines the relationship type in the database, as well as which direction that relationship goes in.

To add two node types, "Movie" and "Actor", and connect the two:

[source, graphql, indent=0]
----
type Movie {
    title: String
    actors: [Actor!]! @relationship(type: "ACTED_IN", direction: IN)
}

type Actor {
    name: String
    movies: [Movie!]! @relationship(type: "ACTED_IN", direction: OUT)
}
----

[NOTE]
====
The `@relationship` directive is used twice, once on each end of the relationship.
This is the standard way of modeling a relationship with the GraphQL library.
However, it is not a requirement of the type definitions themselves and relationships can deliberately be underspecified, for example to limit access through the API layer.
====

 Also see xref::/directives/schema-configuration/field-configuration/#_relationship[`@relationship` field configuration].

== `@relationshipProperties`

=== Definition

[source, graphql, indent=0]
----
"""Required to differentiate between interfaces for relationship properties, and otherwise."""
directive @relationshipProperties on OBJECT
----

`@relationshipProperties` can only be used on interfaces.

=== Usage

In order to add properties to a relationship, add a new type to your type definitions decorated with the `@relationshipProperties` directive.

For example, for the "ACTED_IN" relationship, add a property "roles":

[source, graphql, indent=0]
----
type Movie {
    title: String
    actors: [Actor!]! @relationship(type: "ACTED_IN", direction: IN, properties: "ActedIn")
}

type Actor {
    name: String
    movies: [Movie!]! @relationship(type: "ACTED_IN", direction: OUT, properties: "ActedIn")
}

type ActedIn @relationshipProperties {
    roles: [String]
}
----

Note that in addition to this type, there is an added key `properties` in the existing `@relationship` directives.
For more information, see xref::/types/relationships.adoc[Type definitions -> Relationships].


== `@node`

=== Definition

// tba

=== Usage

The most basic mapping uses GraphQL type names to map to a Neo4j node label.
For example, to represent a node with the label "Movie" and a single property "title" of type string:

[source, graphql, indent=0]
----
type Movie {
    title: String
}
----

With the `@node` directive, you have more control over this mapping, and you can specify the configuration of a GraphQL object type which represents a Neo4j node.

==== The `labels` parameter

You can append the optional parameters `labels` to a GraphQL object with the `@node` directive.
This parameter lists the labels to be used in Neo4j instead of the GraphQL type name.

.Querying a field with the `labels` parameter
====
Consider the following type definition:

[source, graphql, indent=0]
----
type Dog @node(labels: ["K9"]) {
    name: String!
}
----

Here is a query against the `Dog` node:

[source, graphql, indent=0]
----
{
  dogs {
    name
  }
}
----

The following Cypher is generated:

[source, cypher, indent=0]
----
MATCH (this: K9)
RETURN this { .name } as name
----
====

If you want to use the GraphQL type name as a label, specifiy both.

.Querying a field with two entries for the `labels` parameter
====
Consider the following type definition:

[source, graphql, indent=0]
----
type Dog @node(labels: ["Dog", "K9"]) {
    name: String!
}
----

Here is an example for a query against the `Dog` node 


[source, graphql, indent=0]
----
{
  dogs {
    name
  }
}
----

The following Cypher is generated:

[source, cypher, indent=0]
----
MATCH (this:Dog:K9)
RETURN this { .name } as this
----
====

[NOTE]
====
Defining `labels` means you take control of the database labels of the node. 
Indexes and constraints in Neo4j only support a single label, for which the first element of the `labels` argument is used.
====

The following example results in a unique constraint to be asserted for the label `K9` and the property `name`:

[source, graphql, indent=0]
----
type Dog @node(labels: ["K9", "Dog"]) {
    name: String! @unique
}
----

See xref::/directives/indexes-and-constraints.adoc#_unique_node_property_constraints[`@unique`] to learn more about the `@unique` directive.


==== Using `$jwt` and `$context`

In some cases, you may want to generate dynamic labels depending on the user requesting. 
You can use the variable `$jwt` to define a custom label in the JWT.


.Querying a field with a `$jwt` variable in the `labels` parameter
====
Consider the following type definition:

[source, graphql, indent=0]
----
type User @node(labels: ["$jwt.username"]) {
    name: String!
}
----

The following query yields a different Cypher query depending on the user JWT:

[source, graphql, indent=0]
----
{
  users {
    name
  }
}
----

Assuming there is a user with the value `"username": "arthur"` in JWT, the Cypher query looks like this:

[source, cypher, indent=0]
----
MATCH (this:arthur)
RETURN this { .name } as this
----
====

Similarly, context values can be passed directly:

[source, graphql, indent=0]
----
type User @node(label: ["$context.appId"]) {
    name: String!
}
----

For example, if you are running the server with Apollo:

[source, js, indent=0]
----
const server = new ApolloServer({
    schema: await neoSchema.getSchema(),
});

await startStandaloneServer(server, {
    context: async ({ req }) => ({ req, appId: "myApp" }),
});
----


== `@alias`

=== Definition

// tba

=== Usage

This directive maps a GraphQL field to a Neo4j property on a node or relationship.
It can be used on any fields that are not `@cypher` or `@relationship` fields.

For example:

[source, graphql, indent=0]
----
type User {
    id: ID! @id @alias(property: "dbId")
    username: String!
}
----

[source, graphql, indent=0]
----
type User {
    id: ID! @id
    username: String! @alias(property: "dbUserName")
    livesIn: [City!]! @relationship(direction: OUT, type: "LIVES_IN", properties: "UserLivesInProperties")
}

type City {
    name: String
}

type UserLivesInProperties @relationshipProperties {
    since: DateTime @alias(property: "moveInDate")
}
----

[NOTE]
The property in aliases are automatically escaped (wrapped with backticks ``), so there is no need to add escape characters around them.