[[type-definitions-indexes-and-constraints]]
:description: This page describes how to use indexes and constraints in the Neo4j GraphQL Library.
= Indexes and constraints
:page-aliases: type-definitions/indexes-and-constraints.adoc

This page describes how to use indexes and constraints in the Neo4j GraphQL Library.

== Unique node property constraints

Unique node property constraints map to `@unique` directives used in your type definitions, which has the following definition:

[source, graphql, indent=0]
----
"""Informs @neo4j/graphql that there should be a uniqueness constraint in the database for the decorated field."""
directive @unique(
    """The name which should be used for this constraint"""
    constraintName: String!
) on FIELD_DEFINITION
----

Using this directive does not automatically ensure the existence of these constraints, and you will need to run a function on server startup. 
See the section xref::/directives/indexes-and-constraints.adoc#_asserting_constraints[Asserting constraints] for details.

=== Usage

`@unique` directives can only be used in GraphQL object types representing nodes, and they are only applicable for the "main" label for the node.

In the following example, a unique constraint with name `unique_color` is asserted for the label `Color` and the property `hexadecimal`:

[source, graphql, indent=0]
----
type Color @node {
    hexadecimal: String! @unique(constraintName: "unique_color")
}
----

The `@node` directive is used to change the database label mapping in this next example, so a unique constraint is asserted for the first label in the list, `Color`, and the property `hexadecimal`:

[source, graphql, indent=0]
----
type Color @node(labels: ["Color"]) {
    hexadecimal: String! @unique(constraintName: "unique_color")
}
----

In the following example, all labels specified in the `labels` argument of the `@node` directive are also checked when asserting constraints.
If there is a unique constraint specified for the `hexadecimal` property of nodes with the `Hue` label, but not the `Color` label, no error is thrown and no new constraints are created when running `assertIndexesAndConstraints`.

[source, graphql, indent=0]
----
type Color @node(labels: ["Color", "Hue"]) {
    hexadecimal: String! @unique(constraintName: "unique_color")
}
----

== Asserting constraints

In order to ensure that the specified constraints exist in the database, you need to run the function `assertIndexesAndConstraints`.
The following example demonstrates how to assert the constraints for the `Color` type:

[source, javascript, indent=0]
----
const typeDefs = `#graphql
    type Color @node {
        id: ID! @id
        hexadecimal: String! @unique(constraintName: "unique_color")
    }
`;

const neoSchema = new Neo4jGraphQL({ typeDefs, driver });

const schema = await neoSchema.getSchema();

await neoSchema.assertIndexesAndConstraints();
----
