[[directives-reference]]
= Directives reference


== `@alias`

The `@alias` directive will map a GraphQL schema field to a Neo4j property on a node or relationship.

Reference: xref::reference/directives/database-mapping.adoc#type-definitions-alias[`@alias`]

== `@coalesce`

The `@coalesce` directive exposes a mechanism for querying against non-existent, `null` values on a node.

Reference: xref::/directives/default-values.adoc#type-definitions-default-values-coalesce[`@coalesce`]

[[custom-resolver-directive]]
== `@customResolver`

The `@customResolver` directive specifies that a field will be resolved by a custom resolver, and allows the specification
of any required fields that will be passed as arguments to the custom resolver.

Reference: xref::custom-resolvers.adoc#custom-resolver-directive[`@customResolver`]

== `@cypher`

The `@cypher` directive overrides field resolution (including `Query` and `Mutation` fields), instead resolving with the specified Cypher.

Reference: xref::/directives/cypher.adoc[`@cypher` directive]

== `@default`

The `@default` directive allows for the setting of a default value for a field on object creation.

Reference: xref::/directives/default-values.adoc#type-definitions-default-values-default[`@default`]

== `@exclude` label:deprecated[]

This directive is deprecated.

Use the xref:/schema-configuration/type-configuration.adoc#_query[`@query`], xref:/schema-configuration/type-configuration.adoc#_mutation[`@mutation`] and the xref:/schema-configuration/type-configuration.adoc#_subscription[`@subscription`] directives instead.

The `@exclude` directive is used on object types to instruct them to be skipped during Query, Mutation and Subscription generation.

Reference: xref::/schema-configuration/type-configuration.adoc#_exclude_deprecated[`@exclude`]

== `@filterable`

The `@filterable` directive defines the filters generated for a field. 

Reference: xref:/schema-configuration/field-configuration.adoc#_filterable[`@filterable`]

== `@fulltext`

The `@fulltext` directive indicates that there should be a Fulltext index inserted into the database for the specified Node and its properties.

Reference: xref::/directives/indexes-and-constraints.adoc#type-definitions-indexes-fulltext[Fulltext indexes]

== `@id`

The `@id` directive marks a field as the unique ID for an object type, and allows for autogeneration of IDs.

Reference: xref::/directives/autogeneration.adoc#type-definitions-autogeneration-id[`@id`]

== `@limit`

The `@limit` is to be used on nodes, and when applied will inject values into Cypher `LIMIT` clauses.

Reference: xref::reference/directives/default-values.adoc#type-definitions-default-values-limit[`@limit`]

== `@mutation`

This directive is used to limit the availability of Mutation operations in the library.

Reference: xref:/schema-configuration/type-configuration.adoc#_mutation[`@mutation`]

== `@node`

The `@node` directive is used to specify the configuration of a GraphQL object type which represents a Neo4j node.

Reference: xref::/directives/database-mapping.adoc#type-definitions-node[`@node`]

[[plural-directive]]
== `@plural`

The `@plural` directive redefines how to compose the plural of the type for the generated operations.
This is particularly useful for types that are not correctly pluralized or are non-English words.

Reference: xref::/directives/database-mapping.adoc#type-definitions-plural[`@plural`]

[[populated-by-directive]]
== `@populatedBy`

The `@populatedBy` directive is used to specify a callback function that gets executed during GraphQL query parsing,
to populate fields which have not been provided within the input.

Reference: xref::/directives/autogeneration.adoc#type-definitions-autogeneration-populated-by[`@populatedBy`]

== `@private`

The `@private` directive protects fields which should only be available through the xref::ogm/index.adoc[OGM].

Reference: xref::ogm/private.adoc[`@private` Directive]

== `@query`

This directive is used to limit the availability of Query operations in the library.

Reference: xref:/schema-configuration/type-configuration.adoc#_query[`@query`]

== `@relationship`

The `@relationship` directive is used to configure relationships between object types.

Reference: xref::/type-definitions/relationships.adoc[Relationships], xref::/schema-configuration/field-configuration.adoc#_relationship[`@relationship`]

== `@relationshipProperties`

Required to help you distinguish between interfaces which are used for relationship properties, and otherwise.

Can only be used on interfaces, as per its definition:

[source, graphql, indent=0]
----
"""Required to differentiate between interfaces for relationship properties, and otherwise."""
directive @relationshipProperties on INTERFACE
----

== `@selectable`

The `@selectable` directive sets the availability of fields on queries and aggregations. 

Reference: xref:/schema-configuration/field-configuration.adoc#_selectable[`@selectable`]

== `@settable`

The `@settable` directive sets the availability of fields on the create and update inputs. 

Reference: xref:/schema-configuration/field-configuration.adoc#_settable[`@settable`]

== `@subscription`

This directive is used to limit Subscription operations in the library.

Reference: xref:/schema-configuration/type-configuration.adoc#_subscription[`@subscription`]

== `@timestamp`

The `@timestamp` directive flags fields to be used to store timestamps on create/update events.

Reference: xref::/directives/autogeneration.adoc#type-definitions-autogeneration-timestamp[`@timestamp`]

== `@unique`

The `@unique` directive indicates that there should be a uniqueness constraint in the database for the fields that it is applied to.

Reference: xref::reference/type-definitions/indexes-and-constraints.adoc#type-definitions-constraints-unique[Unique node property constraints]
