[[mutations]]
:description: This section describes how to use nested mutations with the Neo4j GraphQL Library.
= Mutations

This section addresses basic examples of the following nested mutations:

- xref::mutations/create.adoc[Create] - Create nodes, and recursively create or connect further nodes in the graph.
- xref::mutations/update.adoc[Update] - Update nodes, and recursively perform any operations from there.
- xref::mutations/delete.adoc[Delete] - Delete nodes, and recursively delete or disconnect further nodes in the graph.

[NOTE]
====
In order to provide the abstractions available in these mutations, the output Cypher can end up being complex.
This can result in your database throwing out-of-memory errors depending on its configuration.

If this becomes a regular occurrence, you can adjust the link:https://neo4j.com/docs/operations-manual/current/configuration/configuration-settings/#config_server.memory.heap.max_size[`server.memory.heap.max_size`] parameter in the DBMS settings.
If you need to perform major data migrations, it may be best to manually write the necessary Cypher and execute this directly in the database.
====